<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:t="http://www.gtk.org/introspection/core/1.0" xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:glib="http://www.gtk.org/introspection/glib/1.0">
<xsl:output method="text" omit-xml-declaration="yes" indent="no"/>
<xsl:strip-space elements="*"/>
<xsl:param name="namespace"/>

<xsl:template match="/main/rs/ns[@namespace=$namespace]/renderstruct[@render='1']">
<xsl:variable name="t" select="."/>
<xsl:result-document href="test/{$namespace}/{$t/@name}.pony" method="text">
<xsl:value-of select="/main/rs/ns[@namespace=$namespace]/ponydep"/>
<xsl:call-template name="mainstruct"><xsl:with-param name="n" select="$t/@name"/></xsl:call-template>
</xsl:result-document>
</xsl:template>
<xsl:template match="/main/rs/ns[@namespace=$namespace]/renderclass[@render='1']">
<xsl:variable name="t" select="."/>
<xsl:result-document href="test/{$namespace}/{$t/@name}.pony" method="text">
<xsl:value-of select="/main/rs/ns[@namespace=$namespace]/ponydep"/>
<xsl:call-template name="mainstruct"><xsl:with-param name="n" select="$t/@name"/></xsl:call-template>
</xsl:result-document>
</xsl:template>

<xsl:template name="mainstruct">
  <xsl:param name="n"/>
  <xsl:variable name="root" select="/main/c2pony/structs/struct[@name=concat($n, 'T')]"/>
  <xsl:text>struct </xsl:text><xsl:value-of select="$root/@name"/><xsl:text>
</xsl:text>
    <xsl:for-each select="$root/field">
      <xsl:text>  </xsl:text><xsl:value-of select="./@decl"/><xsl:text> </xsl:text><xsl:value-of select="./@name"/>: <xsl:value-of select="./@structtype"/><xsl:text> = </xsl:text><xsl:value-of select="./@structinit"/><xsl:text>
</xsl:text>
    </xsl:for-each>
</xsl:template>
<!--
<xsl:template match="(/castxml2pony/rs/ns/renderstruct[@render='0'] | /castxml2pony/rs/ns/renderstruct[@render='1'])">
  <xsl:variable name="iid" select="./@name"/>
  <xsl:variable name="siid" select="concat('S', $iid)"/>
  <xsl:call-template name="mainstruct"><xsl:with-param name="n" select="/castxml2pony/structs/struct[@name=$siid]"/><xsl:with-param name="renderfields" select="@render"/></xsl:call-template> 
</xsl:template>

<xsl:template match="/castxml2pony/rs/ns/renderclass[@render='1']">
  <xsl:variable name="iid" select="./@name"/>
  <xsl:variable name="siid" select="concat('S', $iid)"/>
  <xsl:call-template name="mainstruct"><xsl:with-param name="n" select="/castxml2pony/structs/struct[@name=$siid]"/><xsl:with-param name="renderfields" select="@render"/></xsl:call-template> 
</xsl:template>

<xsl:template name="mainstruct">
<xsl:param name="n" />
<xsl:param name="renderfields" />
<xsl:variable name="fid" select="$n/@fid"/>
<xsl:variable name="originalid" select="$n/@id"/>
<xsl:variable name="origname" select="/castxml2pony/CastXML/Struct[@id=$originalid]/@name"/>
<xsl:result-document href="autogenerated_structs/{$origname}" method="text">
<xsl:text>

/*
  Source: </xsl:text>
    <xsl:message>[<xsl:value-of select="/castxml2pony/CastXML/Struct[@id=$originalid]/@name"/>]<xsl:value-of select="/castxml2pony/CastXML/File[@id=$fid]/@name"/>:<xsl:value-of select="$n/@lineno"/></xsl:message>
    <xsl:value-of select="/castxml2pony/CastXML/File[@id=$fid]/@name"/>:<xsl:value-of select="$n/@lineno"/>
  Original Name: <xsl:value-of select="/castxml2pony/CastXML/Struct[@id=$originalid]/@name"/>
  Struct Size (bits):  <xsl:value-of select="$n/@size"/>
  Struct Align (bits): <xsl:value-of select="$n/@align"/>

  Fields (Offset in bits):
<xsl:apply-templates select="$n/field" mode="generateCommentField"/>*/
struct <xsl:value-of select="$n/@name"/><xsl:text>
</xsl:text>

<xsl:if test="$renderfields='1'"><xsl:apply-templates select="$n/field" mode="generateField"/></xsl:if>
</xsl:result-document>
</xsl:template>

<xsl:template match="field" mode="generateField">
<xsl:variable name="key" select="@type"/>
<xsl:value-of select="/castxml2pony/typedefs/typedef[@name=$key]/@decl"/><xsl:value-of select="@name"/>
<xsl:text>: </xsl:text>
<xsl:variable name="fieldid" select="@fieldid"/>
<xsl:variable name="ffid" select="@fid"/>
<xsl:value-of select="/castxml2pony/typedefs/typedef[@name=$key]/@structtype"/>
<xsl:text> = </xsl:text>
<xsl:value-of select="/castxml2pony/typedefs/typedef[@name=$key]/@structdef"/><xsl:text>
</xsl:text>
</xsl:template>

<xsl:template match="field" mode="generateCommentField">
<xsl:variable name="fieldkey" select="@id"/>
<xsl:variable name="tkey" select="@fieldid"/>
<xsl:variable name="ffid" select="@fid"/>
<xsl:variable name="n" select="/castxml2pony/CastXML/*[@id=$tkey]"/>
<xsl:text>     </xsl:text><xsl:value-of select="format-number(@offset, '000000')"/>: <xsl:call-template name="recurse">
  <xsl:with-param name="node" select="/castxml2pony/CastXML/*[@id=$tkey]"/>
</xsl:call-template>: <xsl:value-of select="/castxml2pony/CastXML/Field[@id=$fieldkey]/@name"/>
<xsl:text>  </xsl:text>
  <xsl:with-param name="str" select="/castxml2pony/CastXML/File[@id=$ffid]/@name"/>
</xsl:call-template>:<xsl:value-of select="@line"/>

<xsl:text>
</xsl:text>
</xsl:template>



<xsl:template name="recurse">
  <xsl:param name="node" />
  <xsl:choose>
    <xsl:when test="name($node) = 'Union'">[UNION size=<xsl:value-of select="$node/@size"/>]  UNSUPPORTED FIXME</xsl:when>
    <xsl:when test="name($node) = 'FunctionType'">[FunctionType]  WRITE MANUALLY</xsl:when>
    <xsl:when test="name($node) = 'Struct'">[Struct size=<xsl:value-of select="$node/@size"/>,fid: <xsl:value-of select="$node/@file"/>]</xsl:when>
    <xsl:when test="name($node) = 'Enumeration'">[Enumeration size=<xsl:value-of select="$node/@size"/>,fid: <xsl:value-of select="$node/@file"/>]</xsl:when>
    <xsl:when test="name($node) = 'FundamentalType'">[FundamentalType(<xsl:value-of select="$node/@name"/>) size=<xsl:value-of select="$node/@size"/>]</xsl:when>
    <xsl:when test="name($node) = 'PointerType'">[PointerType size=<xsl:value-of select="$node/@size"/>]-><xsl:variable name="ttkey" select="$node/@type"/> 
      <xsl:call-template name="recurse">
        <xsl:with-param name="node" select="/castxml2pony/CastXML/*[@id=$ttkey]"/>
      </xsl:call-template>
    </xsl:when>

    <xsl:when test="name($node) = 'CvQualifiedType'"><xsl:variable name="ttkey" select="$node/@type"/> 
      <xsl:call-template name="recurse">
        <xsl:with-param name="node" select="/castxml2pony/CastXML/*[@id=$ttkey]"/>
      </xsl:call-template>
    </xsl:when>

    <xsl:when test="name($node) = 'ElaboratedType'"><xsl:variable name="ttkey" select="$node/@type"/> 
      <xsl:call-template name="recurse">
        <xsl:with-param name="node" select="/castxml2pony/CastXML/*[@id=$ttkey]"/>
      </xsl:call-template>
    </xsl:when>

    <xsl:when test="name($node) = 'Typedef'"><xsl:variable name="ttkey" select="$node/@type"/> 
      <xsl:call-template name="recurse">
        <xsl:with-param name="node" select="/castxml2pony/CastXML/*[@id=$ttkey]"/>
      </xsl:call-template>
    </xsl:when>

    <xsl:when test="name($node) = 'ArrayType'">[ArrayType size=(<xsl:value-of select="$node/@min"/>-<xsl:value-of select="$node/@max"/>)]-><xsl:variable name="ttkey" select="$node/@type"/> 
      <xsl:call-template name="recurse">
        <xsl:with-param name="node" select="/castxml2pony/CastXML/*[@id=$ttkey]"/>
      </xsl:call-template>  UNSUPPORTED - FIXME</xsl:when>

    <xsl:otherwise>[UNKNOWN AS OF YET]</xsl:otherwise>
  </xsl:choose>
</xsl:template>




<xsl:template name="fileName">
  <xsl:param name="str" />
  <xsl:choose>
    <xsl:when test="normalize-space(substring-after($str,'/'))">
      <xsl:call-template name="fileName">
        <xsl:with-param name="str" select="substring-after($str,'/')" />
      </xsl:call-template>  
    </xsl:when>
    <xsl:otherwise>
      <xsl:value-of select="$str" />
    </xsl:otherwise>
  </xsl:choose>
</xsl:template>
-->
<xsl:template match="prefix"></xsl:template>
<xsl:template match="suffix"></xsl:template>
<xsl:template match="text()"></xsl:template>

</xsl:stylesheet>
