
use "../GLib"
use "../Gio"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4"
// use @gtk_accelerator_get_default_mod_mask[U32]()
// use @gtk_accelerator_get_label[Pointer[U8] tag](accelerator_key': U32, accelerator_mods': U32)
// use @gtk_accelerator_get_label_with_keycode[Pointer[U8] tag](display': GdkDisplayT, accelerator_key': U32, keycode': U32, accelerator_mods': U32)
// use @gtk_accelerator_name[Pointer[U8] tag](accelerator_key': U32, accelerator_mods': U32)
// use @gtk_accelerator_name_with_keycode[Pointer[U8] tag](display': GdkDisplayT, accelerator_key': U32, keycode': U32, accelerator_mods': U32)
// use @gtk_accelerator_parse[I32](accelerator': Pointer[U8] tag, accelerator_key': Pointer[U32] tag, accelerator_mods': Pointer[U32] tag)
// use @gtk_accelerator_parse_with_keycode[I32](accelerator': Pointer[U8] tag, display': GdkDisplayT, accelerator_key': Pointer[U32] tag, accelerator_codes': Pointer[Pointer[U32]] tag, accelerator_mods': Pointer[U32] tag)
// use @gtk_accelerator_valid[I32](keyval': U32, modifiers': U32)
// use @gtk_check_version[Pointer[U8] tag](required_major': U32, required_minor': U32, required_micro': U32)
// use @gtk_css_parser_error_quark[U32]()
// use @gtk_css_parser_warning_quark[U32]()
// use @gtk_disable_setlocale[None]()
// use @gtk_distribute_natural_allocation[I32](extra_space': I32, n_requested_sizes': U32, sizes': GtkRequestedSizeT)
// use @gtk_get_binary_age[U32]()
// use @gtk_get_debug_flags[U32]()
// use @gtk_get_default_language[PangoLanguageT]()
// use @gtk_get_interface_age[U32]()
// use @gtk_get_locale_direction[U32]()
// use @gtk_get_major_version[U32]()
// use @gtk_get_micro_version[U32]()
// use @gtk_get_minor_version[U32]()
// use @gtk_hsv_to_rgb[None](h': F32, s': F32, v': F32, r': Pointer[F32] tag, g': Pointer[F32] tag, b': Pointer[F32] tag)
use @gtk_init[None]()
// use @gtk_init_check[I32]()
// use @gtk_is_initialized[I32]()
// use @gtk_param_spec_expression[GParamSpecT](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, flags': I32)
// use @gtk_print_run_page_setup_dialog[GtkPageSetupT](parent': GtkWindowT, page_setup': GtkPageSetupT, settings': GtkPrintSettingsT)
// use @gtk_print_run_page_setup_dialog_async[None](parent': GtkWindowT, page_setup': GtkPageSetupT, settings': GtkPrintSettingsT, done_cb': GtkPageSetupDoneFunc, data': Pointer[None] tag)
// use @gtk_render_activity[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_render_arrow[None](context': GtkStyleContextT, cr': cairoT, angle': F64, x': F64, y': F64, size': F64)
// use @gtk_render_background[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_render_check[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_render_expander[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_render_focus[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_render_frame[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_render_handle[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_render_icon[None](context': GtkStyleContextT, cr': cairoT, texture': GdkTextureT, x': F64, y': F64)
// use @gtk_render_layout[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, layout': PangoLayoutT)
// use @gtk_render_line[None](context': GtkStyleContextT, cr': cairoT, x0': F64, y0': F64, x1': F64, y1': F64)
// use @gtk_render_option[None](context': GtkStyleContextT, cr': cairoT, x': F64, y': F64, width': F64, height': F64)
// use @gtk_rgb_to_hsv[None](r': F32, g': F32, b': F32, h': Pointer[F32] tag, s': Pointer[F32] tag, v': Pointer[F32] tag)
// use @gtk_set_debug_flags[None](flags': U32)
// use @gtk_show_about_dialog[None](parent': GtkWindowT, first_property_name': Pointer[U8] tag, ...)
// use @gtk_show_uri[None](parent': GtkWindowT, uri': Pointer[U8] tag, timestamp': U32)
// use @gtk_show_uri_full[None](parent': GtkWindowT, uri': Pointer[U8] tag, timestamp': U32, cancellable': GCancellableT, callback': GAsyncReadyCallback, user_data': Pointer[None] tag)
// use @gtk_show_uri_full_finish[I32](parent': GtkWindowT, result': GAsyncResultT, error': Pointer[GErrorT])
// use @gtk_test_accessible_assertion_message_role[None](domain': Pointer[U8] tag, file': Pointer[U8] tag, line': I32, func': Pointer[U8] tag, expr': Pointer[U8] tag, accessible': GtkAccessibleT, expected_role': U32, actual_role': U32)
// use @gtk_test_accessible_check_property[Pointer[U8] tag](accessible': GtkAccessibleT, property': U32, ...)
// use @gtk_test_accessible_check_relation[Pointer[U8] tag](accessible': GtkAccessibleT, relation': U32, ...)
// use @gtk_test_accessible_check_state[Pointer[U8] tag](accessible': GtkAccessibleT, state': U32, ...)
// use @gtk_test_accessible_has_property[I32](accessible': GtkAccessibleT, property': U32)
// use @gtk_test_accessible_has_relation[I32](accessible': GtkAccessibleT, relation': U32)
// use @gtk_test_accessible_has_role[I32](accessible': GtkAccessibleT, role': U32)
// use @gtk_test_accessible_has_state[I32](accessible': GtkAccessibleT, state': U32)
// use @gtk_test_init[None](argcp': Pointer[I32] tag, argvp': Pointer[Pointer[Pointer[U8]]] tag, ...)
// use @gtk_test_list_all_types[Pointer[U64] tag](n_types': Pointer[U32] tag)
// use @gtk_test_register_all_types[None]()
// use @gtk_test_widget_wait_for_draw[None](widget': GtkWidgetT)
// use @gtk_tree_create_row_drag_content[GdkContentProviderT](tree_model': GtkTreeModelT, path': GtkTreePathT)
// use @gtk_tree_get_row_drag_data[I32](value': GValueT, tree_model': Pointer[GtkTreeModelT], path': Pointer[GtkTreePathT])
// use @gtk_value_dup_expression[GtkExpressionT](value': GValueT)
// use @gtk_value_get_expression[GtkExpressionT](value': GValueT)
// use @gtk_value_set_expression[None](value': GValueT, expression': GtkExpressionT)
// use @gtk_value_take_expression[None](value': GValueT, expression': GtkExpressionT)
