
use "../P"
use "../GLib"
use "../Gio"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4"

// Static Functions

// Constructors
// use @gtk_print_settings_new[GtkPrintSettingsT]()
// use @gtk_print_settings_new_from_file[GtkPrintSettingsT](file_name': Pointer[U8] tag, error': Pointer[GErrorT])
// use @gtk_print_settings_new_from_gvariant[GtkPrintSettingsT](variant': GVariantT)
// use @gtk_print_settings_new_from_key_file[GtkPrintSettingsT](key_file': GKeyFileT, group_name': Pointer[U8] tag, error': Pointer[GErrorT])

// Methods
// use @gtk_print_settings_copy[GtkPrintSettingsT](other': GtkPrintSettingsT)
// use @gtk_print_settings_foreach[None](settings': GtkPrintSettingsT, func': GtkPrintSettingsFunc, user_data': Pointer[None] tag)
// use @gtk_print_settings_get[Pointer[U8] tag](settings': GtkPrintSettingsT, key': Pointer[U8] tag)
// use @gtk_print_settings_get_bool[I32](settings': GtkPrintSettingsT, key': Pointer[U8] tag)
// use @gtk_print_settings_get_collate[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_default_source[Pointer[U8] tag](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_dither[Pointer[U8] tag](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_double[F64](settings': GtkPrintSettingsT, key': Pointer[U8] tag)
// use @gtk_print_settings_get_double_with_default[F64](settings': GtkPrintSettingsT, key': Pointer[U8] tag, def': F64)
// use @gtk_print_settings_get_duplex[U32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_finishings[Pointer[U8] tag](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_int[I32](settings': GtkPrintSettingsT, key': Pointer[U8] tag)
// use @gtk_print_settings_get_int_with_default[I32](settings': GtkPrintSettingsT, key': Pointer[U8] tag, def': I32)
// use @gtk_print_settings_get_length[F64](settings': GtkPrintSettingsT, key': Pointer[U8] tag, unit': U32)
// use @gtk_print_settings_get_media_type[Pointer[U8] tag](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_n_copies[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_number_up[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_number_up_layout[U32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_orientation[U32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_output_bin[Pointer[U8] tag](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_page_ranges[GtkPageRangeT](settings': GtkPrintSettingsT, num_ranges': Pointer[I32] tag)
// use @gtk_print_settings_get_page_set[U32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_paper_height[F64](settings': GtkPrintSettingsT, unit': U32)
// use @gtk_print_settings_get_paper_size[GtkPaperSizeT](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_paper_width[F64](settings': GtkPrintSettingsT, unit': U32)
// use @gtk_print_settings_get_print_pages[U32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_printer[Pointer[U8] tag](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_printer_lpi[F64](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_quality[U32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_resolution[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_resolution_x[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_resolution_y[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_reverse[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_scale[F64](settings': GtkPrintSettingsT)
// use @gtk_print_settings_get_use_color[I32](settings': GtkPrintSettingsT)
// use @gtk_print_settings_has_key[I32](settings': GtkPrintSettingsT, key': Pointer[U8] tag)
// use @gtk_print_settings_load_file[I32](settings': GtkPrintSettingsT, file_name': Pointer[U8] tag, error': Pointer[GErrorT])
// use @gtk_print_settings_load_key_file[I32](settings': GtkPrintSettingsT, key_file': GKeyFileT, group_name': Pointer[U8] tag, error': Pointer[GErrorT])
// use @gtk_print_settings_set[None](settings': GtkPrintSettingsT, key': Pointer[U8] tag, value': Pointer[U8] tag)
// use @gtk_print_settings_set_bool[None](settings': GtkPrintSettingsT, key': Pointer[U8] tag, value': I32)
// use @gtk_print_settings_set_collate[None](settings': GtkPrintSettingsT, collate': I32)
// use @gtk_print_settings_set_default_source[None](settings': GtkPrintSettingsT, default_source': Pointer[U8] tag)
// use @gtk_print_settings_set_dither[None](settings': GtkPrintSettingsT, dither': Pointer[U8] tag)
// use @gtk_print_settings_set_double[None](settings': GtkPrintSettingsT, key': Pointer[U8] tag, value': F64)
// use @gtk_print_settings_set_duplex[None](settings': GtkPrintSettingsT, duplex': U32)
// use @gtk_print_settings_set_finishings[None](settings': GtkPrintSettingsT, finishings': Pointer[U8] tag)
// use @gtk_print_settings_set_int[None](settings': GtkPrintSettingsT, key': Pointer[U8] tag, value': I32)
// use @gtk_print_settings_set_length[None](settings': GtkPrintSettingsT, key': Pointer[U8] tag, value': F64, unit': U32)
// use @gtk_print_settings_set_media_type[None](settings': GtkPrintSettingsT, media_type': Pointer[U8] tag)
// use @gtk_print_settings_set_n_copies[None](settings': GtkPrintSettingsT, num_copies': I32)
// use @gtk_print_settings_set_number_up[None](settings': GtkPrintSettingsT, number_up': I32)
// use @gtk_print_settings_set_number_up_layout[None](settings': GtkPrintSettingsT, number_up_layout': U32)
// use @gtk_print_settings_set_orientation[None](settings': GtkPrintSettingsT, orientation': U32)
// use @gtk_print_settings_set_output_bin[None](settings': GtkPrintSettingsT, output_bin': Pointer[U8] tag)
// use @gtk_print_settings_set_page_ranges[None](settings': GtkPrintSettingsT, page_ranges': GtkPageRangeT, num_ranges': I32)
// use @gtk_print_settings_set_page_set[None](settings': GtkPrintSettingsT, page_set': U32)
// use @gtk_print_settings_set_paper_height[None](settings': GtkPrintSettingsT, height': F64, unit': U32)
// use @gtk_print_settings_set_paper_size[None](settings': GtkPrintSettingsT, paper_size': GtkPaperSizeT)
// use @gtk_print_settings_set_paper_width[None](settings': GtkPrintSettingsT, width': F64, unit': U32)
// use @gtk_print_settings_set_print_pages[None](settings': GtkPrintSettingsT, pages': U32)
// use @gtk_print_settings_set_printer[None](settings': GtkPrintSettingsT, printer': Pointer[U8] tag)
// use @gtk_print_settings_set_printer_lpi[None](settings': GtkPrintSettingsT, lpi': F64)
// use @gtk_print_settings_set_quality[None](settings': GtkPrintSettingsT, quality': U32)
// use @gtk_print_settings_set_resolution[None](settings': GtkPrintSettingsT, resolution': I32)
// use @gtk_print_settings_set_resolution_xy[None](settings': GtkPrintSettingsT, resolution_x': I32, resolution_y': I32)
// use @gtk_print_settings_set_reverse[None](settings': GtkPrintSettingsT, reverse': I32)
// use @gtk_print_settings_set_scale[None](settings': GtkPrintSettingsT, scale': F64)
// use @gtk_print_settings_set_use_color[None](settings': GtkPrintSettingsT, use_color': I32)
// use @gtk_print_settings_to_file[I32](settings': GtkPrintSettingsT, file_name': Pointer[U8] tag, error': Pointer[GErrorT])
// use @gtk_print_settings_to_gvariant[GVariantT](settings': GtkPrintSettingsT)
// use @gtk_print_settings_to_key_file[None](settings': GtkPrintSettingsT, key_file': GKeyFileT, group_name': Pointer[U8] tag)
// use @gtk_print_settings_unset[None](settings': GtkPrintSettingsT, key': Pointer[U8] tag)
