
use "../GLib"
use "../Gio"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4"

// Static Functions

// Constructors
// use @gtk_tree_view_new[GtkWidgetT]()
// use @gtk_tree_view_new_with_model[GtkWidgetT](model': GtkTreeModelT)

// Methods
// use @gtk_tree_view_append_column[I32](tree_view': GtkTreeViewT, column': GtkTreeViewColumnT)
// use @gtk_tree_view_collapse_all[None](tree_view': GtkTreeViewT)
// use @gtk_tree_view_collapse_row[I32](tree_view': GtkTreeViewT, path': GtkTreePathT)
// use @gtk_tree_view_columns_autosize[None](tree_view': GtkTreeViewT)
// use @gtk_tree_view_convert_bin_window_to_tree_coords[None](tree_view': GtkTreeViewT, bx': I32, by': I32, tx': Pointer[I32] tag, ty': Pointer[I32] tag)
// use @gtk_tree_view_convert_bin_window_to_widget_coords[None](tree_view': GtkTreeViewT, bx': I32, by': I32, wx': Pointer[I32] tag, wy': Pointer[I32] tag)
// use @gtk_tree_view_convert_tree_to_bin_window_coords[None](tree_view': GtkTreeViewT, tx': I32, ty': I32, bx': Pointer[I32] tag, by': Pointer[I32] tag)
// use @gtk_tree_view_convert_tree_to_widget_coords[None](tree_view': GtkTreeViewT, tx': I32, ty': I32, wx': Pointer[I32] tag, wy': Pointer[I32] tag)
// use @gtk_tree_view_convert_widget_to_bin_window_coords[None](tree_view': GtkTreeViewT, wx': I32, wy': I32, bx': Pointer[I32] tag, by': Pointer[I32] tag)
// use @gtk_tree_view_convert_widget_to_tree_coords[None](tree_view': GtkTreeViewT, wx': I32, wy': I32, tx': Pointer[I32] tag, ty': Pointer[I32] tag)
// use @gtk_tree_view_create_row_drag_icon[GdkPaintableT](tree_view': GtkTreeViewT, path': GtkTreePathT)
// use @gtk_tree_view_enable_model_drag_dest[None](tree_view': GtkTreeViewT, formats': GdkContentFormatsT, actions': U32)
// use @gtk_tree_view_enable_model_drag_source[None](tree_view': GtkTreeViewT, start_button_mask': U32, formats': GdkContentFormatsT, actions': U32)
// use @gtk_tree_view_expand_all[None](tree_view': GtkTreeViewT)
// use @gtk_tree_view_expand_row[I32](tree_view': GtkTreeViewT, path': GtkTreePathT, open_all': I32)
// use @gtk_tree_view_expand_to_path[None](tree_view': GtkTreeViewT, path': GtkTreePathT)
// use @gtk_tree_view_get_activate_on_single_click[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_background_area[None](tree_view': GtkTreeViewT, path': GtkTreePathT, column': GtkTreeViewColumnT, rect': cairorectangleintT)
// use @gtk_tree_view_get_cell_area[None](tree_view': GtkTreeViewT, path': GtkTreePathT, column': GtkTreeViewColumnT, rect': cairorectangleintT)
// use @gtk_tree_view_get_column[GtkTreeViewColumnT](tree_view': GtkTreeViewT, n': I32)
// use @gtk_tree_view_get_columns[GListT](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_cursor[None](tree_view': GtkTreeViewT, path': Pointer[GtkTreePathT], focus_column': Pointer[GtkTreeViewColumnT])
// use @gtk_tree_view_get_dest_row_at_pos[I32](tree_view': GtkTreeViewT, drag_x': I32, drag_y': I32, path': Pointer[GtkTreePathT], pos': Pointer[U32] tag)
// use @gtk_tree_view_get_drag_dest_row[None](tree_view': GtkTreeViewT, path': Pointer[GtkTreePathT], pos': Pointer[U32] tag)
// use @gtk_tree_view_get_enable_search[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_enable_tree_lines[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_expander_column[GtkTreeViewColumnT](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_fixed_height_mode[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_grid_lines[U32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_headers_clickable[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_headers_visible[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_hover_expand[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_hover_selection[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_level_indentation[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_model[GtkTreeModelT](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_n_columns[U32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_path_at_pos[I32](tree_view': GtkTreeViewT, x': I32, y': I32, path': Pointer[GtkTreePathT], column': Pointer[GtkTreeViewColumnT], cell_x': Pointer[I32] tag, cell_y': Pointer[I32] tag)
// use @gtk_tree_view_get_reorderable[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_row_separator_func[GtkTreeViewRowSeparatorFunc](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_rubber_banding[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_search_column[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_search_entry[GtkEditableT](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_search_equal_func[GtkTreeViewSearchEqualFunc](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_selection[GtkTreeSelectionT](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_show_expanders[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_tooltip_column[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_get_tooltip_context[I32](tree_view': GtkTreeViewT, x': I32, y': I32, keyboard_tip': I32, model': Pointer[GtkTreeModelT], path': Pointer[GtkTreePathT], iter': GtkTreeIterT)
// use @gtk_tree_view_get_visible_range[I32](tree_view': GtkTreeViewT, start_path': Pointer[GtkTreePathT], end_path': Pointer[GtkTreePathT])
// use @gtk_tree_view_get_visible_rect[None](tree_view': GtkTreeViewT, visible_rect': cairorectangleintT)
// use @gtk_tree_view_insert_column[I32](tree_view': GtkTreeViewT, column': GtkTreeViewColumnT, position': I32)
// use @gtk_tree_view_insert_column_with_attributes[I32](tree_view': GtkTreeViewT, position': I32, title': Pointer[U8] tag, cell': GtkCellRendererT, ...)
// use @gtk_tree_view_insert_column_with_data_func[I32](tree_view': GtkTreeViewT, position': I32, title': Pointer[U8] tag, cell': GtkCellRendererT, func': GtkTreeCellDataFunc, data': Pointer[None] tag, dnotify': GDestroyNotify)
// use @gtk_tree_view_is_blank_at_pos[I32](tree_view': GtkTreeViewT, x': I32, y': I32, path': Pointer[GtkTreePathT], column': Pointer[GtkTreeViewColumnT], cell_x': Pointer[I32] tag, cell_y': Pointer[I32] tag)
// use @gtk_tree_view_is_rubber_banding_active[I32](tree_view': GtkTreeViewT)
// use @gtk_tree_view_map_expanded_rows[None](tree_view': GtkTreeViewT, func': GtkTreeViewMappingFunc, data': Pointer[None] tag)
// use @gtk_tree_view_move_column_after[None](tree_view': GtkTreeViewT, column': GtkTreeViewColumnT, base_column': GtkTreeViewColumnT)
// use @gtk_tree_view_remove_column[I32](tree_view': GtkTreeViewT, column': GtkTreeViewColumnT)
// use @gtk_tree_view_row_activated[None](tree_view': GtkTreeViewT, path': GtkTreePathT, column': GtkTreeViewColumnT)
// use @gtk_tree_view_row_expanded[I32](tree_view': GtkTreeViewT, path': GtkTreePathT)
// use @gtk_tree_view_scroll_to_cell[None](tree_view': GtkTreeViewT, path': GtkTreePathT, column': GtkTreeViewColumnT, use_align': I32, row_align': F32, col_align': F32)
// use @gtk_tree_view_scroll_to_point[None](tree_view': GtkTreeViewT, tree_x': I32, tree_y': I32)
// use @gtk_tree_view_set_activate_on_single_click[None](tree_view': GtkTreeViewT, single': I32)
// use @gtk_tree_view_set_column_drag_function[None](tree_view': GtkTreeViewT, func': GtkTreeViewColumnDropFunc, user_data': Pointer[None] tag, destroy': GDestroyNotify)
// use @gtk_tree_view_set_cursor[None](tree_view': GtkTreeViewT, path': GtkTreePathT, focus_column': GtkTreeViewColumnT, start_editing': I32)
// use @gtk_tree_view_set_cursor_on_cell[None](tree_view': GtkTreeViewT, path': GtkTreePathT, focus_column': GtkTreeViewColumnT, focus_cell': GtkCellRendererT, start_editing': I32)
// use @gtk_tree_view_set_drag_dest_row[None](tree_view': GtkTreeViewT, path': GtkTreePathT, pos': U32)
// use @gtk_tree_view_set_enable_search[None](tree_view': GtkTreeViewT, enable_search': I32)
// use @gtk_tree_view_set_enable_tree_lines[None](tree_view': GtkTreeViewT, enabled': I32)
// use @gtk_tree_view_set_expander_column[None](tree_view': GtkTreeViewT, column': GtkTreeViewColumnT)
// use @gtk_tree_view_set_fixed_height_mode[None](tree_view': GtkTreeViewT, enable': I32)
// use @gtk_tree_view_set_grid_lines[None](tree_view': GtkTreeViewT, grid_lines': U32)
// use @gtk_tree_view_set_headers_clickable[None](tree_view': GtkTreeViewT, setting': I32)
// use @gtk_tree_view_set_headers_visible[None](tree_view': GtkTreeViewT, headers_visible': I32)
// use @gtk_tree_view_set_hover_expand[None](tree_view': GtkTreeViewT, expand': I32)
// use @gtk_tree_view_set_hover_selection[None](tree_view': GtkTreeViewT, hover': I32)
// use @gtk_tree_view_set_level_indentation[None](tree_view': GtkTreeViewT, indentation': I32)
// use @gtk_tree_view_set_model[None](tree_view': GtkTreeViewT, model': GtkTreeModelT)
// use @gtk_tree_view_set_reorderable[None](tree_view': GtkTreeViewT, reorderable': I32)
// use @gtk_tree_view_set_row_separator_func[None](tree_view': GtkTreeViewT, func': GtkTreeViewRowSeparatorFunc, data': Pointer[None] tag, destroy': GDestroyNotify)
// use @gtk_tree_view_set_rubber_banding[None](tree_view': GtkTreeViewT, enable': I32)
// use @gtk_tree_view_set_search_column[None](tree_view': GtkTreeViewT, column': I32)
// use @gtk_tree_view_set_search_entry[None](tree_view': GtkTreeViewT, entry': GtkEditableT)
// use @gtk_tree_view_set_search_equal_func[None](tree_view': GtkTreeViewT, search_equal_func': GtkTreeViewSearchEqualFunc, search_user_data': Pointer[None] tag, search_destroy': GDestroyNotify)
// use @gtk_tree_view_set_show_expanders[None](tree_view': GtkTreeViewT, enabled': I32)
// use @gtk_tree_view_set_tooltip_cell[None](tree_view': GtkTreeViewT, tooltip': GtkTooltipT, path': GtkTreePathT, column': GtkTreeViewColumnT, cell': GtkCellRendererT)
// use @gtk_tree_view_set_tooltip_column[None](tree_view': GtkTreeViewT, column': I32)
// use @gtk_tree_view_set_tooltip_row[None](tree_view': GtkTreeViewT, tooltip': GtkTooltipT, path': GtkTreePathT)
// use @gtk_tree_view_unset_rows_drag_dest[None](tree_view': GtkTreeViewT)
// use @gtk_tree_view_unset_rows_drag_source[None](tree_view': GtkTreeViewT)
