
use "../P"
use "../GLib"
use "../Gio"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4"

// Static Functions

// Constructors
// use @gtk_text_view_new[GtkWidgetT]()
// use @gtk_text_view_new_with_buffer[GtkWidgetT](buffer': GtkTextBufferT)

// Methods
// use @gtk_text_view_add_child_at_anchor[None](text_view': GtkTextViewT, child': GtkWidgetT, anchor': GtkTextChildAnchorT)
// use @gtk_text_view_add_overlay[None](text_view': GtkTextViewT, child': GtkWidgetT, xpos': I32, ypos': I32)
// use @gtk_text_view_backward_display_line[I32](text_view': GtkTextViewT, iter': GtkTextIterT)
// use @gtk_text_view_backward_display_line_start[I32](text_view': GtkTextViewT, iter': GtkTextIterT)
// use @gtk_text_view_buffer_to_window_coords[None](text_view': GtkTextViewT, win': U32, buffer_x': I32, buffer_y': I32, window_x': Pointer[I32] tag, window_y': Pointer[I32] tag)
// use @gtk_text_view_forward_display_line[I32](text_view': GtkTextViewT, iter': GtkTextIterT)
// use @gtk_text_view_forward_display_line_end[I32](text_view': GtkTextViewT, iter': GtkTextIterT)
// use @gtk_text_view_get_accepts_tab[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_bottom_margin[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_buffer[GtkTextBufferT](text_view': GtkTextViewT)
// use @gtk_text_view_get_cursor_locations[None](text_view': GtkTextViewT, iter': GtkTextIterT, strong': cairorectangleintT, weak': cairorectangleintT)
// use @gtk_text_view_get_cursor_visible[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_editable[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_extra_menu[GMenuModelT](text_view': GtkTextViewT)
// use @gtk_text_view_get_gutter[GtkWidgetT](text_view': GtkTextViewT, win': U32)
// use @gtk_text_view_get_indent[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_input_hints[U32](text_view': GtkTextViewT)
// use @gtk_text_view_get_input_purpose[U32](text_view': GtkTextViewT)
// use @gtk_text_view_get_iter_at_location[I32](text_view': GtkTextViewT, iter': GtkTextIterT, x': I32, y': I32)
// use @gtk_text_view_get_iter_at_position[I32](text_view': GtkTextViewT, iter': GtkTextIterT, trailing': Pointer[I32] tag, x': I32, y': I32)
// use @gtk_text_view_get_iter_location[None](text_view': GtkTextViewT, iter': GtkTextIterT, location': cairorectangleintT)
// use @gtk_text_view_get_justification[U32](text_view': GtkTextViewT)
// use @gtk_text_view_get_left_margin[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_line_at_y[None](text_view': GtkTextViewT, target_iter': GtkTextIterT, y': I32, line_top': Pointer[I32] tag)
// use @gtk_text_view_get_line_yrange[None](text_view': GtkTextViewT, iter': GtkTextIterT, y': Pointer[I32] tag, height': Pointer[I32] tag)
// use @gtk_text_view_get_ltr_context[PangoContextT](text_view': GtkTextViewT)
// use @gtk_text_view_get_monospace[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_overwrite[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_pixels_above_lines[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_pixels_below_lines[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_pixels_inside_wrap[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_right_margin[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_rtl_context[PangoContextT](text_view': GtkTextViewT)
// use @gtk_text_view_get_tabs[PangoTabArrayT](text_view': GtkTextViewT)
// use @gtk_text_view_get_top_margin[I32](text_view': GtkTextViewT)
// use @gtk_text_view_get_visible_rect[None](text_view': GtkTextViewT, visible_rect': cairorectangleintT)
// use @gtk_text_view_get_wrap_mode[U32](text_view': GtkTextViewT)
// use @gtk_text_view_im_context_filter_keypress[I32](text_view': GtkTextViewT, event': GdkEventT)
// use @gtk_text_view_move_mark_onscreen[I32](text_view': GtkTextViewT, mark': GtkTextMarkT)
// use @gtk_text_view_move_overlay[None](text_view': GtkTextViewT, child': GtkWidgetT, xpos': I32, ypos': I32)
// use @gtk_text_view_move_visually[I32](text_view': GtkTextViewT, iter': GtkTextIterT, count': I32)
// use @gtk_text_view_place_cursor_onscreen[I32](text_view': GtkTextViewT)
// use @gtk_text_view_remove[None](text_view': GtkTextViewT, child': GtkWidgetT)
// use @gtk_text_view_reset_cursor_blink[None](text_view': GtkTextViewT)
// use @gtk_text_view_reset_im_context[None](text_view': GtkTextViewT)
// use @gtk_text_view_scroll_mark_onscreen[None](text_view': GtkTextViewT, mark': GtkTextMarkT)
// use @gtk_text_view_scroll_to_iter[I32](text_view': GtkTextViewT, iter': GtkTextIterT, within_margin': F64, use_align': I32, xalign': F64, yalign': F64)
// use @gtk_text_view_scroll_to_mark[None](text_view': GtkTextViewT, mark': GtkTextMarkT, within_margin': F64, use_align': I32, xalign': F64, yalign': F64)
// use @gtk_text_view_set_accepts_tab[None](text_view': GtkTextViewT, accepts_tab': I32)
// use @gtk_text_view_set_bottom_margin[None](text_view': GtkTextViewT, bottom_margin': I32)
// use @gtk_text_view_set_buffer[None](text_view': GtkTextViewT, buffer': GtkTextBufferT)
// use @gtk_text_view_set_cursor_visible[None](text_view': GtkTextViewT, setting': I32)
// use @gtk_text_view_set_editable[None](text_view': GtkTextViewT, setting': I32)
// use @gtk_text_view_set_extra_menu[None](text_view': GtkTextViewT, model': GMenuModelT)
// use @gtk_text_view_set_gutter[None](text_view': GtkTextViewT, win': U32, widget': GtkWidgetT)
// use @gtk_text_view_set_indent[None](text_view': GtkTextViewT, indent': I32)
// use @gtk_text_view_set_input_hints[None](text_view': GtkTextViewT, hints': U32)
// use @gtk_text_view_set_input_purpose[None](text_view': GtkTextViewT, purpose': U32)
// use @gtk_text_view_set_justification[None](text_view': GtkTextViewT, justification': U32)
// use @gtk_text_view_set_left_margin[None](text_view': GtkTextViewT, left_margin': I32)
// use @gtk_text_view_set_monospace[None](text_view': GtkTextViewT, monospace': I32)
// use @gtk_text_view_set_overwrite[None](text_view': GtkTextViewT, overwrite': I32)
// use @gtk_text_view_set_pixels_above_lines[None](text_view': GtkTextViewT, pixels_above_lines': I32)
// use @gtk_text_view_set_pixels_below_lines[None](text_view': GtkTextViewT, pixels_below_lines': I32)
// use @gtk_text_view_set_pixels_inside_wrap[None](text_view': GtkTextViewT, pixels_inside_wrap': I32)
// use @gtk_text_view_set_right_margin[None](text_view': GtkTextViewT, right_margin': I32)
// use @gtk_text_view_set_tabs[None](text_view': GtkTextViewT, tabs': PangoTabArrayT)
// use @gtk_text_view_set_top_margin[None](text_view': GtkTextViewT, top_margin': I32)
// use @gtk_text_view_set_wrap_mode[None](text_view': GtkTextViewT, wrap_mode': U32)
// use @gtk_text_view_starts_display_line[I32](text_view': GtkTextViewT, iter': GtkTextIterT)
// use @gtk_text_view_window_to_buffer_coords[None](text_view': GtkTextViewT, win': U32, window_x': I32, window_y': I32, buffer_x': Pointer[I32] tag, buffer_y': Pointer[I32] tag)
