
use "../GLib"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4.0"

// Static Functions

// Constructors
// use @gtk_text_buffer_new[Pointer[GtkTextBufferT]](table': NullablePointer[GtkTextTagTableT])

// Methods
// use @gtk_text_buffer_add_mark[None](buffer': NullablePointer[GtkTextBufferT], mark': NullablePointer[GtkTextMarkT], where': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_add_selection_clipboard[None](buffer': NullablePointer[GtkTextBufferT], clipboard': NullablePointer[GdkClipboardT])
// use @gtk_text_buffer_apply_tag[None](buffer': NullablePointer[GtkTextBufferT], tag': NullablePointer[GtkTextTagT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_apply_tag_by_name[None](buffer': NullablePointer[GtkTextBufferT], name': Pointer[U8] tag, start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_backspace[I32](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], interactive': I32, default_editable': I32)
// use @gtk_text_buffer_begin_irreversible_action[None](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_begin_user_action[None](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_copy_clipboard[None](buffer': NullablePointer[GtkTextBufferT], clipboard': NullablePointer[GdkClipboardT])
// use @gtk_text_buffer_create_child_anchor[Pointer[GtkTextChildAnchorT]](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_create_mark[Pointer[GtkTextMarkT]](buffer': NullablePointer[GtkTextBufferT], mark_name': Pointer[U8] tag, where': NullablePointer[GtkTextIterT], left_gravity': I32)
// use @gtk_text_buffer_create_tag[Pointer[GtkTextTagT]](buffer': NullablePointer[GtkTextBufferT], tag_name': Pointer[U8] tag, first_property_name': Pointer[U8] tag, ...)
// use @gtk_text_buffer_cut_clipboard[None](buffer': NullablePointer[GtkTextBufferT], clipboard': NullablePointer[GdkClipboardT], default_editable': I32)
// use @gtk_text_buffer_delete[None](buffer': NullablePointer[GtkTextBufferT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_delete_interactive[I32](buffer': NullablePointer[GtkTextBufferT], start_iter': NullablePointer[GtkTextIterT], end_iter': NullablePointer[GtkTextIterT], default_editable': I32)
// use @gtk_text_buffer_delete_mark[None](buffer': NullablePointer[GtkTextBufferT], mark': NullablePointer[GtkTextMarkT])
// use @gtk_text_buffer_delete_mark_by_name[None](buffer': NullablePointer[GtkTextBufferT], name': Pointer[U8] tag)
// use @gtk_text_buffer_delete_selection[I32](buffer': NullablePointer[GtkTextBufferT], interactive': I32, default_editable': I32)
// use @gtk_text_buffer_end_irreversible_action[None](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_end_user_action[None](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_bounds[None](buffer': NullablePointer[GtkTextBufferT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_get_can_redo[I32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_can_undo[I32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_char_count[I32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_enable_undo[I32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_end_iter[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_get_has_selection[I32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_insert[Pointer[GtkTextMarkT]](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_iter_at_child_anchor[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], anchor': NullablePointer[GtkTextChildAnchorT])
// use @gtk_text_buffer_get_iter_at_line[I32](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], line_number': I32)
// use @gtk_text_buffer_get_iter_at_line_index[I32](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], line_number': I32, byte_index': I32)
// use @gtk_text_buffer_get_iter_at_line_offset[I32](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], line_number': I32, char_offset': I32)
// use @gtk_text_buffer_get_iter_at_mark[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], mark': NullablePointer[GtkTextMarkT])
// use @gtk_text_buffer_get_iter_at_offset[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], char_offset': I32)
// use @gtk_text_buffer_get_line_count[I32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_mark[Pointer[GtkTextMarkT]](buffer': NullablePointer[GtkTextBufferT], name': Pointer[U8] tag)
// use @gtk_text_buffer_get_max_undo_levels[U32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_modified[I32](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_selection_bound[Pointer[GtkTextMarkT]](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_selection_bounds[I32](buffer': NullablePointer[GtkTextBufferT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_get_selection_content[Pointer[GdkContentProviderT]](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_slice[Pointer[U8]](buffer': NullablePointer[GtkTextBufferT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT], include_hidden_chars': I32)
// use @gtk_text_buffer_get_start_iter[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_get_tag_table[Pointer[GtkTextTagTableT]](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_get_text[Pointer[U8]](buffer': NullablePointer[GtkTextBufferT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT], include_hidden_chars': I32)
// use @gtk_text_buffer_insert[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], text': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_insert_at_cursor[None](buffer': NullablePointer[GtkTextBufferT], text': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_insert_child_anchor[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], anchor': NullablePointer[GtkTextChildAnchorT])
// use @gtk_text_buffer_insert_interactive[I32](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], text': Pointer[U8] tag, len': I32, default_editable': I32)
// use @gtk_text_buffer_insert_interactive_at_cursor[I32](buffer': NullablePointer[GtkTextBufferT], text': Pointer[U8] tag, len': I32, default_editable': I32)
// use @gtk_text_buffer_insert_markup[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], markup': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_insert_paintable[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], paintable': NullablePointer[GdkPaintableT])
// use @gtk_text_buffer_insert_range[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_insert_range_interactive[I32](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT], default_editable': I32)
// use @gtk_text_buffer_insert_with_tags[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], text': Pointer[U8] tag, len': I32, first_tag': NullablePointer[GtkTextTagT], ...)
// use @gtk_text_buffer_insert_with_tags_by_name[None](buffer': NullablePointer[GtkTextBufferT], iter': NullablePointer[GtkTextIterT], text': Pointer[U8] tag, len': I32, first_tag_name': Pointer[U8] tag, ...)
// use @gtk_text_buffer_move_mark[None](buffer': NullablePointer[GtkTextBufferT], mark': NullablePointer[GtkTextMarkT], where': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_move_mark_by_name[None](buffer': NullablePointer[GtkTextBufferT], name': Pointer[U8] tag, where': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_paste_clipboard[None](buffer': NullablePointer[GtkTextBufferT], clipboard': NullablePointer[GdkClipboardT], override_location': NullablePointer[GtkTextIterT], default_editable': I32)
// use @gtk_text_buffer_place_cursor[None](buffer': NullablePointer[GtkTextBufferT], where': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_redo[None](buffer': NullablePointer[GtkTextBufferT])
// use @gtk_text_buffer_remove_all_tags[None](buffer': NullablePointer[GtkTextBufferT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_remove_selection_clipboard[None](buffer': NullablePointer[GtkTextBufferT], clipboard': NullablePointer[GdkClipboardT])
// use @gtk_text_buffer_remove_tag[None](buffer': NullablePointer[GtkTextBufferT], tag': NullablePointer[GtkTextTagT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_remove_tag_by_name[None](buffer': NullablePointer[GtkTextBufferT], name': Pointer[U8] tag, start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_select_range[None](buffer': NullablePointer[GtkTextBufferT], ins': NullablePointer[GtkTextIterT], bound': NullablePointer[GtkTextIterT])
// use @gtk_text_buffer_set_enable_undo[None](buffer': NullablePointer[GtkTextBufferT], enable_undo': I32)
// use @gtk_text_buffer_set_max_undo_levels[None](buffer': NullablePointer[GtkTextBufferT], max_undo_levels': U32)
// use @gtk_text_buffer_set_modified[None](buffer': NullablePointer[GtkTextBufferT], setting': I32)
// use @gtk_text_buffer_set_text[None](buffer': NullablePointer[GtkTextBufferT], text': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_undo[None](buffer': NullablePointer[GtkTextBufferT])
