
use "../GLib"
use "../Gio"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4"

// Static Functions

// Constructors
// use @gtk_text_buffer_new[GtkTextBufferT](table': GtkTextTagTableT)

// Methods
// use @gtk_text_buffer_add_mark[None](buffer': GtkTextBufferT, mark': GtkTextMarkT, where': GtkTextIterT)
// use @gtk_text_buffer_add_selection_clipboard[None](buffer': GtkTextBufferT, clipboard': GdkClipboardT)
// use @gtk_text_buffer_apply_tag[None](buffer': GtkTextBufferT, tag': GtkTextTagT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_apply_tag_by_name[None](buffer': GtkTextBufferT, name': Pointer[U8] tag, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_backspace[I32](buffer': GtkTextBufferT, iter': GtkTextIterT, interactive': I32, default_editable': I32)
// use @gtk_text_buffer_begin_irreversible_action[None](buffer': GtkTextBufferT)
// use @gtk_text_buffer_begin_user_action[None](buffer': GtkTextBufferT)
// use @gtk_text_buffer_copy_clipboard[None](buffer': GtkTextBufferT, clipboard': GdkClipboardT)
// use @gtk_text_buffer_create_child_anchor[GtkTextChildAnchorT](buffer': GtkTextBufferT, iter': GtkTextIterT)
// use @gtk_text_buffer_create_mark[GtkTextMarkT](buffer': GtkTextBufferT, mark_name': Pointer[U8] tag, where': GtkTextIterT, left_gravity': I32)
// use @gtk_text_buffer_create_tag[GtkTextTagT](buffer': GtkTextBufferT, tag_name': Pointer[U8] tag, first_property_name': Pointer[U8] tag, ...)
// use @gtk_text_buffer_cut_clipboard[None](buffer': GtkTextBufferT, clipboard': GdkClipboardT, default_editable': I32)
// use @gtk_text_buffer_delete[None](buffer': GtkTextBufferT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_delete_interactive[I32](buffer': GtkTextBufferT, start_iter': GtkTextIterT, end_iter': GtkTextIterT, default_editable': I32)
// use @gtk_text_buffer_delete_mark[None](buffer': GtkTextBufferT, mark': GtkTextMarkT)
// use @gtk_text_buffer_delete_mark_by_name[None](buffer': GtkTextBufferT, name': Pointer[U8] tag)
// use @gtk_text_buffer_delete_selection[I32](buffer': GtkTextBufferT, interactive': I32, default_editable': I32)
// use @gtk_text_buffer_end_irreversible_action[None](buffer': GtkTextBufferT)
// use @gtk_text_buffer_end_user_action[None](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_bounds[None](buffer': GtkTextBufferT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_get_can_redo[I32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_can_undo[I32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_char_count[I32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_enable_undo[I32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_end_iter[None](buffer': GtkTextBufferT, iter': GtkTextIterT)
// use @gtk_text_buffer_get_has_selection[I32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_insert[GtkTextMarkT](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_iter_at_child_anchor[None](buffer': GtkTextBufferT, iter': GtkTextIterT, anchor': GtkTextChildAnchorT)
// use @gtk_text_buffer_get_iter_at_line[I32](buffer': GtkTextBufferT, iter': GtkTextIterT, line_number': I32)
// use @gtk_text_buffer_get_iter_at_line_index[I32](buffer': GtkTextBufferT, iter': GtkTextIterT, line_number': I32, byte_index': I32)
// use @gtk_text_buffer_get_iter_at_line_offset[I32](buffer': GtkTextBufferT, iter': GtkTextIterT, line_number': I32, char_offset': I32)
// use @gtk_text_buffer_get_iter_at_mark[None](buffer': GtkTextBufferT, iter': GtkTextIterT, mark': GtkTextMarkT)
// use @gtk_text_buffer_get_iter_at_offset[None](buffer': GtkTextBufferT, iter': GtkTextIterT, char_offset': I32)
// use @gtk_text_buffer_get_line_count[I32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_mark[GtkTextMarkT](buffer': GtkTextBufferT, name': Pointer[U8] tag)
// use @gtk_text_buffer_get_max_undo_levels[U32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_modified[I32](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_selection_bound[GtkTextMarkT](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_selection_bounds[I32](buffer': GtkTextBufferT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_get_selection_content[GdkContentProviderT](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_slice[Pointer[U8] tag](buffer': GtkTextBufferT, start': GtkTextIterT, end': GtkTextIterT, include_hidden_chars': I32)
// use @gtk_text_buffer_get_start_iter[None](buffer': GtkTextBufferT, iter': GtkTextIterT)
// use @gtk_text_buffer_get_tag_table[GtkTextTagTableT](buffer': GtkTextBufferT)
// use @gtk_text_buffer_get_text[Pointer[U8] tag](buffer': GtkTextBufferT, start': GtkTextIterT, end': GtkTextIterT, include_hidden_chars': I32)
// use @gtk_text_buffer_insert[None](buffer': GtkTextBufferT, iter': GtkTextIterT, text': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_insert_at_cursor[None](buffer': GtkTextBufferT, text': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_insert_child_anchor[None](buffer': GtkTextBufferT, iter': GtkTextIterT, anchor': GtkTextChildAnchorT)
// use @gtk_text_buffer_insert_interactive[I32](buffer': GtkTextBufferT, iter': GtkTextIterT, text': Pointer[U8] tag, len': I32, default_editable': I32)
// use @gtk_text_buffer_insert_interactive_at_cursor[I32](buffer': GtkTextBufferT, text': Pointer[U8] tag, len': I32, default_editable': I32)
// use @gtk_text_buffer_insert_markup[None](buffer': GtkTextBufferT, iter': GtkTextIterT, markup': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_insert_paintable[None](buffer': GtkTextBufferT, iter': GtkTextIterT, paintable': GdkPaintableT)
// use @gtk_text_buffer_insert_range[None](buffer': GtkTextBufferT, iter': GtkTextIterT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_insert_range_interactive[I32](buffer': GtkTextBufferT, iter': GtkTextIterT, start': GtkTextIterT, end': GtkTextIterT, default_editable': I32)
// use @gtk_text_buffer_insert_with_tags[None](buffer': GtkTextBufferT, iter': GtkTextIterT, text': Pointer[U8] tag, len': I32, first_tag': GtkTextTagT, ...)
// use @gtk_text_buffer_insert_with_tags_by_name[None](buffer': GtkTextBufferT, iter': GtkTextIterT, text': Pointer[U8] tag, len': I32, first_tag_name': Pointer[U8] tag, ...)
// use @gtk_text_buffer_move_mark[None](buffer': GtkTextBufferT, mark': GtkTextMarkT, where': GtkTextIterT)
// use @gtk_text_buffer_move_mark_by_name[None](buffer': GtkTextBufferT, name': Pointer[U8] tag, where': GtkTextIterT)
// use @gtk_text_buffer_paste_clipboard[None](buffer': GtkTextBufferT, clipboard': GdkClipboardT, override_location': GtkTextIterT, default_editable': I32)
// use @gtk_text_buffer_place_cursor[None](buffer': GtkTextBufferT, where': GtkTextIterT)
// use @gtk_text_buffer_redo[None](buffer': GtkTextBufferT)
// use @gtk_text_buffer_remove_all_tags[None](buffer': GtkTextBufferT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_remove_selection_clipboard[None](buffer': GtkTextBufferT, clipboard': GdkClipboardT)
// use @gtk_text_buffer_remove_tag[None](buffer': GtkTextBufferT, tag': GtkTextTagT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_remove_tag_by_name[None](buffer': GtkTextBufferT, name': Pointer[U8] tag, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_buffer_select_range[None](buffer': GtkTextBufferT, ins': GtkTextIterT, bound': GtkTextIterT)
// use @gtk_text_buffer_set_enable_undo[None](buffer': GtkTextBufferT, enable_undo': I32)
// use @gtk_text_buffer_set_max_undo_levels[None](buffer': GtkTextBufferT, max_undo_levels': U32)
// use @gtk_text_buffer_set_modified[None](buffer': GtkTextBufferT, setting': I32)
// use @gtk_text_buffer_set_text[None](buffer': GtkTextBufferT, text': Pointer[U8] tag, len': I32)
// use @gtk_text_buffer_undo[None](buffer': GtkTextBufferT)
