
use "../GLib"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4.0"

// Static Functions

// Constructors

// Methods
// use @gtk_text_iter_assign[None](iter': NullablePointer[GtkTextIterT], other': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_char[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_chars[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_backward_cursor_position[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_cursor_positions[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_backward_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_lines[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_backward_search[I32](iter': NullablePointer[GtkTextIterT], str': Pointer[U8] tag, flags': U32, match_start': NullablePointer[GtkTextIterT], match_end': NullablePointer[GtkTextIterT], limit': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_sentence_start[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_sentence_starts[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_backward_to_tag_toggle[I32](iter': NullablePointer[GtkTextIterT], tag': NullablePointer[GtkTextTagT])
// use @gtk_text_iter_backward_visible_cursor_position[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_visible_cursor_positions[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_backward_visible_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_visible_lines[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_backward_visible_word_start[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_visible_word_starts[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_backward_word_start[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_backward_word_starts[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_can_insert[I32](iter': NullablePointer[GtkTextIterT], default_editability': I32)
// use @gtk_text_iter_compare[I32](lhs': NullablePointer[GtkTextIterT], rhs': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_copy[Pointer[GtkTextIterT]](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_editable[I32](iter': NullablePointer[GtkTextIterT], default_setting': I32)
// use @gtk_text_iter_ends_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_ends_sentence[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_ends_tag[I32](iter': NullablePointer[GtkTextIterT], tag': NullablePointer[GtkTextTagT])
// use @gtk_text_iter_ends_word[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_equal[I32](lhs': NullablePointer[GtkTextIterT], rhs': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_char[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_chars[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_forward_cursor_position[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_cursor_positions[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_forward_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_lines[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_forward_search[I32](iter': NullablePointer[GtkTextIterT], str': Pointer[U8] tag, flags': U32, match_start': NullablePointer[GtkTextIterT], match_end': NullablePointer[GtkTextIterT], limit': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_sentence_end[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_sentence_ends[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_forward_to_end[None](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_to_line_end[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_to_tag_toggle[I32](iter': NullablePointer[GtkTextIterT], tag': NullablePointer[GtkTextTagT])
// use @gtk_text_iter_forward_visible_cursor_position[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_visible_cursor_positions[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_forward_visible_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_visible_lines[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_forward_visible_word_end[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_visible_word_ends[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_forward_word_end[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_forward_word_ends[I32](iter': NullablePointer[GtkTextIterT], count': I32)
// use @gtk_text_iter_free[None](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_buffer[Pointer[GtkTextBufferT]](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_bytes_in_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_char[U32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_chars_in_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_child_anchor[Pointer[GtkTextChildAnchorT]](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_language[Pointer[PangoLanguageT]](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_line_index[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_line_offset[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_marks[Pointer[GSListT]](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_offset[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_paintable[Pointer[GdkPaintableT]](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_slice[Pointer[U8]](start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_tags[Pointer[GSListT]](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_text[Pointer[U8]](start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_toggled_tags[Pointer[GSListT]](iter': NullablePointer[GtkTextIterT], toggled_on': I32)
// use @gtk_text_iter_get_visible_line_index[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_visible_line_offset[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_visible_slice[Pointer[U8]](start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_get_visible_text[Pointer[U8]](start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_has_tag[I32](iter': NullablePointer[GtkTextIterT], tag': NullablePointer[GtkTextTagT])
// use @gtk_text_iter_in_range[I32](iter': NullablePointer[GtkTextIterT], start': NullablePointer[GtkTextIterT], end': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_inside_sentence[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_inside_word[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_is_cursor_position[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_is_end[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_is_start[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_order[None](first': NullablePointer[GtkTextIterT], second': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_set_line[None](iter': NullablePointer[GtkTextIterT], line_number': I32)
// use @gtk_text_iter_set_line_index[None](iter': NullablePointer[GtkTextIterT], byte_on_line': I32)
// use @gtk_text_iter_set_line_offset[None](iter': NullablePointer[GtkTextIterT], char_on_line': I32)
// use @gtk_text_iter_set_offset[None](iter': NullablePointer[GtkTextIterT], char_offset': I32)
// use @gtk_text_iter_set_visible_line_index[None](iter': NullablePointer[GtkTextIterT], byte_on_line': I32)
// use @gtk_text_iter_set_visible_line_offset[None](iter': NullablePointer[GtkTextIterT], char_on_line': I32)
// use @gtk_text_iter_starts_line[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_starts_sentence[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_starts_tag[I32](iter': NullablePointer[GtkTextIterT], tag': NullablePointer[GtkTextTagT])
// use @gtk_text_iter_starts_word[I32](iter': NullablePointer[GtkTextIterT])
// use @gtk_text_iter_toggles_tag[I32](iter': NullablePointer[GtkTextIterT], tag': NullablePointer[GtkTextTagT])
