
use "../GLib"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4.0"

// Static Functions

// Constructors
// use @gtk_tree_view_new[Pointer[GtkWidgetT]]()
// use @gtk_tree_view_new_with_model[Pointer[GtkWidgetT]](model': NullablePointer[GtkTreeModelT])

// Methods
// use @gtk_tree_view_append_column[I32](tree_view': NullablePointer[GtkTreeViewT], column': NullablePointer[GtkTreeViewColumnT])
// use @gtk_tree_view_collapse_all[None](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_collapse_row[I32](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT])
// use @gtk_tree_view_columns_autosize[None](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_convert_bin_window_to_tree_coords[None](tree_view': NullablePointer[GtkTreeViewT], bx': I32, by': I32, tx': Pointer[I32] tag, ty': Pointer[I32] tag)
// use @gtk_tree_view_convert_bin_window_to_widget_coords[None](tree_view': NullablePointer[GtkTreeViewT], bx': I32, by': I32, wx': Pointer[I32] tag, wy': Pointer[I32] tag)
// use @gtk_tree_view_convert_tree_to_bin_window_coords[None](tree_view': NullablePointer[GtkTreeViewT], tx': I32, ty': I32, bx': Pointer[I32] tag, by': Pointer[I32] tag)
// use @gtk_tree_view_convert_tree_to_widget_coords[None](tree_view': NullablePointer[GtkTreeViewT], tx': I32, ty': I32, wx': Pointer[I32] tag, wy': Pointer[I32] tag)
// use @gtk_tree_view_convert_widget_to_bin_window_coords[None](tree_view': NullablePointer[GtkTreeViewT], wx': I32, wy': I32, bx': Pointer[I32] tag, by': Pointer[I32] tag)
// use @gtk_tree_view_convert_widget_to_tree_coords[None](tree_view': NullablePointer[GtkTreeViewT], wx': I32, wy': I32, tx': Pointer[I32] tag, ty': Pointer[I32] tag)
// use @gtk_tree_view_create_row_drag_icon[Pointer[GdkPaintableT]](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT])
// use @gtk_tree_view_enable_model_drag_dest[None](tree_view': NullablePointer[GtkTreeViewT], formats': NullablePointer[GdkContentFormatsT], actions': U32)
// use @gtk_tree_view_enable_model_drag_source[None](tree_view': NullablePointer[GtkTreeViewT], start_button_mask': U32, formats': NullablePointer[GdkContentFormatsT], actions': U32)
// use @gtk_tree_view_expand_all[None](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_expand_row[I32](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], open_all': I32)
// use @gtk_tree_view_expand_to_path[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT])
// use @gtk_tree_view_get_activate_on_single_click[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_background_area[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], column': NullablePointer[GtkTreeViewColumnT], rect': NullablePointer[cairorectangleintT])
// use @gtk_tree_view_get_cell_area[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], column': NullablePointer[GtkTreeViewColumnT], rect': NullablePointer[cairorectangleintT])
// use @gtk_tree_view_get_column[Pointer[GtkTreeViewColumnT]](tree_view': NullablePointer[GtkTreeViewT], n': I32)
// use @gtk_tree_view_get_columns[Pointer[GListT]](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_cursor[None](tree_view': NullablePointer[GtkTreeViewT], path': Pointer[NullablePointer[GtkTreePathT]], focus_column': Pointer[NullablePointer[GtkTreeViewColumnT]])
// use @gtk_tree_view_get_dest_row_at_pos[I32](tree_view': NullablePointer[GtkTreeViewT], drag_x': I32, drag_y': I32, path': Pointer[NullablePointer[GtkTreePathT]], pos': Pointer[U32] tag)
// use @gtk_tree_view_get_drag_dest_row[None](tree_view': NullablePointer[GtkTreeViewT], path': Pointer[NullablePointer[GtkTreePathT]], pos': Pointer[U32] tag)
// use @gtk_tree_view_get_enable_search[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_enable_tree_lines[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_expander_column[Pointer[GtkTreeViewColumnT]](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_fixed_height_mode[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_grid_lines[U32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_headers_clickable[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_headers_visible[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_hover_expand[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_hover_selection[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_level_indentation[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_model[Pointer[GtkTreeModelT]](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_n_columns[U32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_path_at_pos[I32](tree_view': NullablePointer[GtkTreeViewT], x': I32, y': I32, path': Pointer[NullablePointer[GtkTreePathT]], column': Pointer[NullablePointer[GtkTreeViewColumnT]], cell_x': Pointer[I32] tag, cell_y': Pointer[I32] tag)
// use @gtk_tree_view_get_reorderable[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_row_separator_func[Pointer[FIXME FunctionType]](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_rubber_banding[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_search_column[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_search_entry[Pointer[GtkEditableT]](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_search_equal_func[Pointer[FIXME FunctionType]](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_selection[Pointer[GtkTreeSelectionT]](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_show_expanders[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_tooltip_column[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_get_tooltip_context[I32](tree_view': NullablePointer[GtkTreeViewT], x': I32, y': I32, keyboard_tip': I32, model': Pointer[NullablePointer[GtkTreeModelT]], path': Pointer[NullablePointer[GtkTreePathT]], iter': NullablePointer[GtkTreeIterT])
// use @gtk_tree_view_get_visible_range[I32](tree_view': NullablePointer[GtkTreeViewT], start_path': Pointer[NullablePointer[GtkTreePathT]], end_path': Pointer[NullablePointer[GtkTreePathT]])
// use @gtk_tree_view_get_visible_rect[None](tree_view': NullablePointer[GtkTreeViewT], visible_rect': NullablePointer[cairorectangleintT])
// use @gtk_tree_view_insert_column[I32](tree_view': NullablePointer[GtkTreeViewT], column': NullablePointer[GtkTreeViewColumnT], position': I32)
// use @gtk_tree_view_insert_column_with_attributes[I32](tree_view': NullablePointer[GtkTreeViewT], position': I32, title': Pointer[U8] tag, cell': NullablePointer[GtkCellRendererT], ...)
// use @gtk_tree_view_is_blank_at_pos[I32](tree_view': NullablePointer[GtkTreeViewT], x': I32, y': I32, path': Pointer[NullablePointer[GtkTreePathT]], column': Pointer[NullablePointer[GtkTreeViewColumnT]], cell_x': Pointer[I32] tag, cell_y': Pointer[I32] tag)
// use @gtk_tree_view_is_rubber_banding_active[I32](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_move_column_after[None](tree_view': NullablePointer[GtkTreeViewT], column': NullablePointer[GtkTreeViewColumnT], base_column': NullablePointer[GtkTreeViewColumnT])
// use @gtk_tree_view_remove_column[I32](tree_view': NullablePointer[GtkTreeViewT], column': NullablePointer[GtkTreeViewColumnT])
// use @gtk_tree_view_row_activated[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], column': NullablePointer[GtkTreeViewColumnT])
// use @gtk_tree_view_row_expanded[I32](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT])
// use @gtk_tree_view_scroll_to_cell[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], column': NullablePointer[GtkTreeViewColumnT], use_align': I32, row_align': F32, col_align': F32)
// use @gtk_tree_view_scroll_to_point[None](tree_view': NullablePointer[GtkTreeViewT], tree_x': I32, tree_y': I32)
// use @gtk_tree_view_set_activate_on_single_click[None](tree_view': NullablePointer[GtkTreeViewT], single': I32)
// use @gtk_tree_view_set_cursor[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], focus_column': NullablePointer[GtkTreeViewColumnT], start_editing': I32)
// use @gtk_tree_view_set_cursor_on_cell[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], focus_column': NullablePointer[GtkTreeViewColumnT], focus_cell': NullablePointer[GtkCellRendererT], start_editing': I32)
// use @gtk_tree_view_set_drag_dest_row[None](tree_view': NullablePointer[GtkTreeViewT], path': NullablePointer[GtkTreePathT], pos': U32)
// use @gtk_tree_view_set_enable_search[None](tree_view': NullablePointer[GtkTreeViewT], enable_search': I32)
// use @gtk_tree_view_set_enable_tree_lines[None](tree_view': NullablePointer[GtkTreeViewT], enabled': I32)
// use @gtk_tree_view_set_expander_column[None](tree_view': NullablePointer[GtkTreeViewT], column': NullablePointer[GtkTreeViewColumnT])
// use @gtk_tree_view_set_fixed_height_mode[None](tree_view': NullablePointer[GtkTreeViewT], enable': I32)
// use @gtk_tree_view_set_grid_lines[None](tree_view': NullablePointer[GtkTreeViewT], grid_lines': U32)
// use @gtk_tree_view_set_headers_clickable[None](tree_view': NullablePointer[GtkTreeViewT], setting': I32)
// use @gtk_tree_view_set_headers_visible[None](tree_view': NullablePointer[GtkTreeViewT], headers_visible': I32)
// use @gtk_tree_view_set_hover_expand[None](tree_view': NullablePointer[GtkTreeViewT], expand': I32)
// use @gtk_tree_view_set_hover_selection[None](tree_view': NullablePointer[GtkTreeViewT], hover': I32)
// use @gtk_tree_view_set_level_indentation[None](tree_view': NullablePointer[GtkTreeViewT], indentation': I32)
// use @gtk_tree_view_set_model[None](tree_view': NullablePointer[GtkTreeViewT], model': NullablePointer[GtkTreeModelT])
// use @gtk_tree_view_set_reorderable[None](tree_view': NullablePointer[GtkTreeViewT], reorderable': I32)
// use @gtk_tree_view_set_rubber_banding[None](tree_view': NullablePointer[GtkTreeViewT], enable': I32)
// use @gtk_tree_view_set_search_column[None](tree_view': NullablePointer[GtkTreeViewT], column': I32)
// use @gtk_tree_view_set_search_entry[None](tree_view': NullablePointer[GtkTreeViewT], entry': NullablePointer[GtkEditableT])
// use @gtk_tree_view_set_show_expanders[None](tree_view': NullablePointer[GtkTreeViewT], enabled': I32)
// use @gtk_tree_view_set_tooltip_cell[None](tree_view': NullablePointer[GtkTreeViewT], tooltip': NullablePointer[GtkTooltipT], path': NullablePointer[GtkTreePathT], column': NullablePointer[GtkTreeViewColumnT], cell': NullablePointer[GtkCellRendererT])
// use @gtk_tree_view_set_tooltip_column[None](tree_view': NullablePointer[GtkTreeViewT], column': I32)
// use @gtk_tree_view_set_tooltip_row[None](tree_view': NullablePointer[GtkTreeViewT], tooltip': NullablePointer[GtkTooltipT], path': NullablePointer[GtkTreePathT])
// use @gtk_tree_view_unset_rows_drag_dest[None](tree_view': NullablePointer[GtkTreeViewT])
// use @gtk_tree_view_unset_rows_drag_source[None](tree_view': NullablePointer[GtkTreeViewT])
