
use "../P"
use "../GLib"
use "../Gio"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4"

// Static Functions

// Constructors

// Methods
// use @gtk_text_iter_assign[None](iter': GtkTextIterT, other': GtkTextIterT)
// use @gtk_text_iter_backward_char[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_chars[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_backward_cursor_position[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_cursor_positions[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_backward_find_char[I32](iter': GtkTextIterT, pred': GtkTextCharPredicate, user_data': Pointer[None] tag, limit': GtkTextIterT)
// use @gtk_text_iter_backward_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_lines[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_backward_search[I32](iter': GtkTextIterT, str': Pointer[U8] tag, flags': U32, match_start': GtkTextIterT, match_end': GtkTextIterT, limit': GtkTextIterT)
// use @gtk_text_iter_backward_sentence_start[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_sentence_starts[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_backward_to_tag_toggle[I32](iter': GtkTextIterT, tag': GtkTextTagT)
// use @gtk_text_iter_backward_visible_cursor_position[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_visible_cursor_positions[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_backward_visible_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_visible_lines[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_backward_visible_word_start[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_visible_word_starts[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_backward_word_start[I32](iter': GtkTextIterT)
// use @gtk_text_iter_backward_word_starts[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_can_insert[I32](iter': GtkTextIterT, default_editability': I32)
// use @gtk_text_iter_compare[I32](lhs': GtkTextIterT, rhs': GtkTextIterT)
// use @gtk_text_iter_copy[GtkTextIterT](iter': GtkTextIterT)
// use @gtk_text_iter_editable[I32](iter': GtkTextIterT, default_setting': I32)
// use @gtk_text_iter_ends_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_ends_sentence[I32](iter': GtkTextIterT)
// use @gtk_text_iter_ends_tag[I32](iter': GtkTextIterT, tag': GtkTextTagT)
// use @gtk_text_iter_ends_word[I32](iter': GtkTextIterT)
// use @gtk_text_iter_equal[I32](lhs': GtkTextIterT, rhs': GtkTextIterT)
// use @gtk_text_iter_forward_char[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_chars[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_forward_cursor_position[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_cursor_positions[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_forward_find_char[I32](iter': GtkTextIterT, pred': GtkTextCharPredicate, user_data': Pointer[None] tag, limit': GtkTextIterT)
// use @gtk_text_iter_forward_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_lines[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_forward_search[I32](iter': GtkTextIterT, str': Pointer[U8] tag, flags': U32, match_start': GtkTextIterT, match_end': GtkTextIterT, limit': GtkTextIterT)
// use @gtk_text_iter_forward_sentence_end[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_sentence_ends[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_forward_to_end[None](iter': GtkTextIterT)
// use @gtk_text_iter_forward_to_line_end[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_to_tag_toggle[I32](iter': GtkTextIterT, tag': GtkTextTagT)
// use @gtk_text_iter_forward_visible_cursor_position[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_visible_cursor_positions[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_forward_visible_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_visible_lines[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_forward_visible_word_end[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_visible_word_ends[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_forward_word_end[I32](iter': GtkTextIterT)
// use @gtk_text_iter_forward_word_ends[I32](iter': GtkTextIterT, count': I32)
// use @gtk_text_iter_free[None](iter': GtkTextIterT)
// use @gtk_text_iter_get_buffer[GtkTextBufferT](iter': GtkTextIterT)
// use @gtk_text_iter_get_bytes_in_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_char[U32](iter': GtkTextIterT)
// use @gtk_text_iter_get_chars_in_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_child_anchor[GtkTextChildAnchorT](iter': GtkTextIterT)
// use @gtk_text_iter_get_language[PangoLanguageT](iter': GtkTextIterT)
// use @gtk_text_iter_get_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_line_index[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_line_offset[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_marks[GSListT](iter': GtkTextIterT)
// use @gtk_text_iter_get_offset[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_paintable[GdkPaintableT](iter': GtkTextIterT)
// use @gtk_text_iter_get_slice[Pointer[U8] tag](start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_iter_get_tags[GSListT](iter': GtkTextIterT)
// use @gtk_text_iter_get_text[Pointer[U8] tag](start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_iter_get_toggled_tags[GSListT](iter': GtkTextIterT, toggled_on': I32)
// use @gtk_text_iter_get_visible_line_index[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_visible_line_offset[I32](iter': GtkTextIterT)
// use @gtk_text_iter_get_visible_slice[Pointer[U8] tag](start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_iter_get_visible_text[Pointer[U8] tag](start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_iter_has_tag[I32](iter': GtkTextIterT, tag': GtkTextTagT)
// use @gtk_text_iter_in_range[I32](iter': GtkTextIterT, start': GtkTextIterT, end': GtkTextIterT)
// use @gtk_text_iter_inside_sentence[I32](iter': GtkTextIterT)
// use @gtk_text_iter_inside_word[I32](iter': GtkTextIterT)
// use @gtk_text_iter_is_cursor_position[I32](iter': GtkTextIterT)
// use @gtk_text_iter_is_end[I32](iter': GtkTextIterT)
// use @gtk_text_iter_is_start[I32](iter': GtkTextIterT)
// use @gtk_text_iter_order[None](first': GtkTextIterT, second': GtkTextIterT)
// use @gtk_text_iter_set_line[None](iter': GtkTextIterT, line_number': I32)
// use @gtk_text_iter_set_line_index[None](iter': GtkTextIterT, byte_on_line': I32)
// use @gtk_text_iter_set_line_offset[None](iter': GtkTextIterT, char_on_line': I32)
// use @gtk_text_iter_set_offset[None](iter': GtkTextIterT, char_offset': I32)
// use @gtk_text_iter_set_visible_line_index[None](iter': GtkTextIterT, byte_on_line': I32)
// use @gtk_text_iter_set_visible_line_offset[None](iter': GtkTextIterT, char_on_line': I32)
// use @gtk_text_iter_starts_line[I32](iter': GtkTextIterT)
// use @gtk_text_iter_starts_sentence[I32](iter': GtkTextIterT)
// use @gtk_text_iter_starts_tag[I32](iter': GtkTextIterT, tag': GtkTextTagT)
// use @gtk_text_iter_starts_word[I32](iter': GtkTextIterT)
// use @gtk_text_iter_toggles_tag[I32](iter': GtkTextIterT, tag': GtkTextTagT)
