
use "../GLib"
use "../Gio"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4"

// Static Functions
// use @gtk_widget_get_default_direction[U32]()
// use @gtk_widget_set_default_direction[None](dir': U32)

// Constructors

// Methods
// use @gtk_widget_action_set_enabled[None](widget': NullablePointer[GtkWidgetT], action_name': Pointer[U8] tag, enabled': I32)
// use @gtk_widget_activate[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_activate_action[I32](widget': NullablePointer[GtkWidgetT], name': Pointer[U8] tag, format_string': Pointer[U8] tag, ...)
// use @gtk_widget_activate_action_variant[I32](widget': NullablePointer[GtkWidgetT], name': Pointer[U8] tag, args': NullablePointer[GVariantT])
// use @gtk_widget_activate_default[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_add_controller[None](widget': NullablePointer[GtkWidgetT], controller': NullablePointer[GtkEventControllerT])
// use @gtk_widget_add_css_class[None](widget': NullablePointer[GtkWidgetT], css_class': Pointer[U8] tag)
// use @gtk_widget_add_mnemonic_label[None](widget': NullablePointer[GtkWidgetT], label': NullablePointer[GtkWidgetT])
// use @gtk_widget_allocate[None](widget': NullablePointer[GtkWidgetT], width': I32, height': I32, baseline': I32, transform': NullablePointer[GskTransformT])
// use @gtk_widget_child_focus[I32](widget': NullablePointer[GtkWidgetT], direction': U32)
// use @gtk_widget_compute_bounds[I32](widget': NullablePointer[GtkWidgetT], target': NullablePointer[GtkWidgetT], out_bounds': NullablePointer[graphenerecttT])
// use @gtk_widget_compute_expand[I32](widget': NullablePointer[GtkWidgetT], orientation': U32)
// use @gtk_widget_compute_point[I32](widget': NullablePointer[GtkWidgetT], target': NullablePointer[GtkWidgetT], point': NullablePointer[graphenepointtT], out_point': NullablePointer[graphenepointtT])
// use @gtk_widget_compute_transform[I32](widget': NullablePointer[GtkWidgetT], target': NullablePointer[GtkWidgetT], out_transform': NullablePointer[graphenematrixtT])
// use @gtk_widget_contains[I32](widget': NullablePointer[GtkWidgetT], x': F64, y': F64)
// use @gtk_widget_create_pango_context[Pointer[PangoContextT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_create_pango_layout[Pointer[PangoLayoutT]](widget': NullablePointer[GtkWidgetT], text': Pointer[U8] tag)
// use @gtk_drag_check_threshold[I32](widget': NullablePointer[GtkWidgetT], start_x': I32, start_y': I32, current_x': I32, current_y': I32)
// use @gtk_widget_error_bell[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_allocated_baseline[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_allocated_height[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_allocated_width[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_allocation[None](widget': NullablePointer[GtkWidgetT], allocation': NullablePointer[cairorectangleintT])
// use @gtk_widget_get_ancestor[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT], widget_type': U64)
// use @gtk_widget_get_can_focus[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_can_target[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_child_visible[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_clipboard[Pointer[GdkClipboardT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_css_classes[Pointer[Pointer[U8]]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_css_name[Pointer[U8]](self': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_cursor[Pointer[GdkCursorT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_direction[U32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_display[Pointer[GdkDisplayT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_first_child[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_focus_child[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_focus_on_click[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_focusable[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_font_map[Pointer[PangoFontMapT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_font_options[Pointer[cairofontoptionsT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_frame_clock[Pointer[GdkFrameClockT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_halign[U32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_has_tooltip[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_height[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_hexpand[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_hexpand_set[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_last_child[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_layout_manager[Pointer[GtkLayoutManagerT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_mapped[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_margin_bottom[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_margin_end[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_margin_start[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_margin_top[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_name[Pointer[U8]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_native[Pointer[GtkNativeT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_next_sibling[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_opacity[F64](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_overflow[U32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_pango_context[Pointer[PangoContextT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_parent[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_preferred_size[None](widget': NullablePointer[GtkWidgetT], minimum_size': NullablePointer[GtkRequisitionT], natural_size': NullablePointer[GtkRequisitionT])
// use @gtk_widget_get_prev_sibling[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_primary_clipboard[Pointer[GdkClipboardT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_realized[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_receives_default[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_request_mode[U32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_root[Pointer[GtkRootT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_scale_factor[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_sensitive[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_settings[Pointer[GtkSettingsT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_size[I32](widget': NullablePointer[GtkWidgetT], orientation': U32)
// use @gtk_widget_get_size_request[None](widget': NullablePointer[GtkWidgetT], width': Pointer[I32] tag, height': Pointer[I32] tag)
// use @gtk_widget_get_state_flags[U32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_style_context[Pointer[GtkStyleContextT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_template_child[Pointer[GObjectT]](widget': NullablePointer[GtkWidgetT], widget_type': U64, name': Pointer[U8] tag)
// use @gtk_widget_get_tooltip_markup[Pointer[U8]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_tooltip_text[Pointer[U8]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_valign[U32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_vexpand[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_vexpand_set[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_visible[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_get_width[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_grab_focus[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_has_css_class[I32](widget': NullablePointer[GtkWidgetT], css_class': Pointer[U8] tag)
// use @gtk_widget_has_default[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_has_focus[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_has_visible_focus[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_hide[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_in_destruction[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_init_template[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_insert_action_group[None](widget': NullablePointer[GtkWidgetT], name': Pointer[U8] tag, group': NullablePointer[GActionGroupT])
// use @gtk_widget_insert_after[None](widget': NullablePointer[GtkWidgetT], parent': NullablePointer[GtkWidgetT], previous_sibling': NullablePointer[GtkWidgetT])
// use @gtk_widget_insert_before[None](widget': NullablePointer[GtkWidgetT], parent': NullablePointer[GtkWidgetT], next_sibling': NullablePointer[GtkWidgetT])
// use @gtk_widget_is_ancestor[I32](widget': NullablePointer[GtkWidgetT], ancestor': NullablePointer[GtkWidgetT])
// use @gtk_widget_is_drawable[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_is_focus[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_is_sensitive[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_is_visible[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_keynav_failed[I32](widget': NullablePointer[GtkWidgetT], direction': U32)
// use @gtk_widget_list_mnemonic_labels[Pointer[GListT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_map[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_measure[None](widget': NullablePointer[GtkWidgetT], orientation': U32, for_size': I32, minimum': Pointer[I32] tag, natural': Pointer[I32] tag, minimum_baseline': Pointer[I32] tag, natural_baseline': Pointer[I32] tag)
// use @gtk_widget_mnemonic_activate[I32](widget': NullablePointer[GtkWidgetT], group_cycling': I32)
// use @gtk_widget_observe_children[Pointer[GListModelT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_observe_controllers[Pointer[GListModelT]](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_pick[Pointer[GtkWidgetT]](widget': NullablePointer[GtkWidgetT], x': F64, y': F64, flags': U32)
// use @gtk_widget_queue_allocate[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_queue_draw[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_queue_resize[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_realize[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_remove_controller[None](widget': NullablePointer[GtkWidgetT], controller': NullablePointer[GtkEventControllerT])
// use @gtk_widget_remove_css_class[None](widget': NullablePointer[GtkWidgetT], css_class': Pointer[U8] tag)
// use @gtk_widget_remove_mnemonic_label[None](widget': NullablePointer[GtkWidgetT], label': NullablePointer[GtkWidgetT])
// use @gtk_widget_remove_tick_callback[None](widget': NullablePointer[GtkWidgetT], id': U32)
// use @gtk_widget_set_can_focus[None](widget': NullablePointer[GtkWidgetT], can_focus': I32)
// use @gtk_widget_set_can_target[None](widget': NullablePointer[GtkWidgetT], can_target': I32)
// use @gtk_widget_set_child_visible[None](widget': NullablePointer[GtkWidgetT], child_visible': I32)
// use @gtk_widget_set_css_classes[None](widget': NullablePointer[GtkWidgetT], classes': Pointer[Pointer[U8]] tag)
// use @gtk_widget_set_cursor[None](widget': NullablePointer[GtkWidgetT], cursor': NullablePointer[GdkCursorT])
// use @gtk_widget_set_cursor_from_name[None](widget': NullablePointer[GtkWidgetT], name': Pointer[U8] tag)
// use @gtk_widget_set_direction[None](widget': NullablePointer[GtkWidgetT], dir': U32)
// use @gtk_widget_set_focus_child[None](widget': NullablePointer[GtkWidgetT], child': NullablePointer[GtkWidgetT])
// use @gtk_widget_set_focus_on_click[None](widget': NullablePointer[GtkWidgetT], focus_on_click': I32)
// use @gtk_widget_set_focusable[None](widget': NullablePointer[GtkWidgetT], focusable': I32)
// use @gtk_widget_set_font_map[None](widget': NullablePointer[GtkWidgetT], font_map': NullablePointer[PangoFontMapT])
// use @gtk_widget_set_font_options[None](widget': NullablePointer[GtkWidgetT], options': NullablePointer[cairofontoptionsT])
// use @gtk_widget_set_halign[None](widget': NullablePointer[GtkWidgetT], align': U32)
// use @gtk_widget_set_has_tooltip[None](widget': NullablePointer[GtkWidgetT], has_tooltip': I32)
// use @gtk_widget_set_hexpand[None](widget': NullablePointer[GtkWidgetT], expand': I32)
// use @gtk_widget_set_hexpand_set[None](widget': NullablePointer[GtkWidgetT], set': I32)
// use @gtk_widget_set_layout_manager[None](widget': NullablePointer[GtkWidgetT], layout_manager': NullablePointer[GtkLayoutManagerT])
// use @gtk_widget_set_margin_bottom[None](widget': NullablePointer[GtkWidgetT], margin': I32)
// use @gtk_widget_set_margin_end[None](widget': NullablePointer[GtkWidgetT], margin': I32)
// use @gtk_widget_set_margin_start[None](widget': NullablePointer[GtkWidgetT], margin': I32)
// use @gtk_widget_set_margin_top[None](widget': NullablePointer[GtkWidgetT], margin': I32)
// use @gtk_widget_set_name[None](widget': NullablePointer[GtkWidgetT], name': Pointer[U8] tag)
// use @gtk_widget_set_opacity[None](widget': NullablePointer[GtkWidgetT], opacity': F64)
// use @gtk_widget_set_overflow[None](widget': NullablePointer[GtkWidgetT], overflow': U32)
// use @gtk_widget_set_parent[None](widget': NullablePointer[GtkWidgetT], parent': NullablePointer[GtkWidgetT])
// use @gtk_widget_set_receives_default[None](widget': NullablePointer[GtkWidgetT], receives_default': I32)
// use @gtk_widget_set_sensitive[None](widget': NullablePointer[GtkWidgetT], sensitive': I32)
// use @gtk_widget_set_size_request[None](widget': NullablePointer[GtkWidgetT], width': I32, height': I32)
// use @gtk_widget_set_state_flags[None](widget': NullablePointer[GtkWidgetT], flags': U32, clear': I32)
// use @gtk_widget_set_tooltip_markup[None](widget': NullablePointer[GtkWidgetT], markup': Pointer[U8] tag)
// use @gtk_widget_set_tooltip_text[None](widget': NullablePointer[GtkWidgetT], text': Pointer[U8] tag)
// use @gtk_widget_set_valign[None](widget': NullablePointer[GtkWidgetT], align': U32)
// use @gtk_widget_set_vexpand[None](widget': NullablePointer[GtkWidgetT], expand': I32)
// use @gtk_widget_set_vexpand_set[None](widget': NullablePointer[GtkWidgetT], set': I32)
// use @gtk_widget_set_visible[None](widget': NullablePointer[GtkWidgetT], visible': I32)
// use @gtk_widget_should_layout[I32](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_show[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_size_allocate[None](widget': NullablePointer[GtkWidgetT], allocation': NullablePointer[cairorectangleintT], baseline': I32)
// use @gtk_widget_snapshot_child[None](widget': NullablePointer[GtkWidgetT], child': NullablePointer[GtkWidgetT], snapshot': NullablePointer[GdkSnapshotT])
// use @gtk_widget_translate_coordinates[I32](src_widget': NullablePointer[GtkWidgetT], dest_widget': NullablePointer[GtkWidgetT], src_x': F64, src_y': F64, dest_x': Pointer[F64] tag, dest_y': Pointer[F64] tag)
// use @gtk_widget_trigger_tooltip_query[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_unmap[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_unparent[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_unrealize[None](widget': NullablePointer[GtkWidgetT])
// use @gtk_widget_unset_state_flags[None](widget': NullablePointer[GtkWidgetT], flags': U32)
