
use "../GLib"
use "../GObject"
//  use "../Gdk"
//  use "../Gsk"
use "lib:gtk-4.0"

// Static Functions
// use @gtk_window_get_default_icon_name[Pointer[U8]]()
// use @gtk_window_get_toplevels[Pointer[GListModelT]]()
// use @gtk_window_list_toplevels[Pointer[GListT]]()
// use @gtk_window_set_auto_startup_notification[None](setting': I32)
// use @gtk_window_set_default_icon_name[None](name': Pointer[U8] tag)
// use @gtk_window_set_interactive_debugging[None](enable': I32)

// Constructors
// use @gtk_window_new[Pointer[GtkWidgetT]]()

// Methods
// use @gtk_window_close[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_destroy[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_fullscreen[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_fullscreen_on_monitor[None](window': NullablePointer[GtkWindowT], monitor': NullablePointer[GdkMonitorT])
// use @gtk_window_get_application[Pointer[GtkApplicationT]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_child[Pointer[GtkWidgetT]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_decorated[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_default_size[None](window': NullablePointer[GtkWindowT], width': Pointer[I32] tag, height': Pointer[I32] tag)
// use @gtk_window_get_default_widget[Pointer[GtkWidgetT]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_deletable[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_destroy_with_parent[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_focus[Pointer[GtkWidgetT]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_focus_visible[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_group[Pointer[GtkWindowGroupT]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_handle_menubar_accel[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_hide_on_close[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_icon_name[Pointer[U8]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_mnemonics_visible[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_modal[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_resizable[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_title[Pointer[U8]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_titlebar[Pointer[GtkWidgetT]](window': NullablePointer[GtkWindowT])
// use @gtk_window_get_transient_for[Pointer[GtkWindowT]](window': NullablePointer[GtkWindowT])
// use @gtk_window_has_group[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_is_active[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_is_fullscreen[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_is_maximized[I32](window': NullablePointer[GtkWindowT])
// use @gtk_window_maximize[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_minimize[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_present[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_present_with_time[None](window': NullablePointer[GtkWindowT], timestamp': U32)
// use @gtk_window_set_application[None](window': NullablePointer[GtkWindowT], application': NullablePointer[GtkApplicationT])
// use @gtk_window_set_child[None](window': NullablePointer[GtkWindowT], child': NullablePointer[GtkWidgetT])
// use @gtk_window_set_decorated[None](window': NullablePointer[GtkWindowT], setting': I32)
// use @gtk_window_set_default_size[None](window': NullablePointer[GtkWindowT], width': I32, height': I32)
// use @gtk_window_set_default_widget[None](window': NullablePointer[GtkWindowT], default_widget': NullablePointer[GtkWidgetT])
// use @gtk_window_set_deletable[None](window': NullablePointer[GtkWindowT], setting': I32)
// use @gtk_window_set_destroy_with_parent[None](window': NullablePointer[GtkWindowT], setting': I32)
// use @gtk_window_set_display[None](window': NullablePointer[GtkWindowT], display': NullablePointer[GdkDisplayT])
// use @gtk_window_set_focus[None](window': NullablePointer[GtkWindowT], focus': NullablePointer[GtkWidgetT])
// use @gtk_window_set_focus_visible[None](window': NullablePointer[GtkWindowT], setting': I32)
// use @gtk_window_set_handle_menubar_accel[None](window': NullablePointer[GtkWindowT], handle_menubar_accel': I32)
// use @gtk_window_set_hide_on_close[None](window': NullablePointer[GtkWindowT], setting': I32)
// use @gtk_window_set_icon_name[None](window': NullablePointer[GtkWindowT], name': Pointer[U8] tag)
// use @gtk_window_set_mnemonics_visible[None](window': NullablePointer[GtkWindowT], setting': I32)
// use @gtk_window_set_modal[None](window': NullablePointer[GtkWindowT], modal': I32)
// use @gtk_window_set_resizable[None](window': NullablePointer[GtkWindowT], resizable': I32)
// use @gtk_window_set_startup_id[None](window': NullablePointer[GtkWindowT], startup_id': Pointer[U8] tag)
// use @gtk_window_set_title[None](window': NullablePointer[GtkWindowT], title': Pointer[U8] tag)
// use @gtk_window_set_titlebar[None](window': NullablePointer[GtkWindowT], titlebar': NullablePointer[GtkWidgetT])
// use @gtk_window_set_transient_for[None](window': NullablePointer[GtkWindowT], parent': NullablePointer[GtkWindowT])
// use @gtk_window_unfullscreen[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_unmaximize[None](window': NullablePointer[GtkWindowT])
// use @gtk_window_unminimize[None](window': NullablePointer[GtkWindowT])
