
use "lib:glib-2.0"

// Static Functions
// use @g_bookmark_file_error_quark[U32]()
// use @g_bookmark_file_new[NullablePointer[GBookmarkFileT]]()

// Constructors

// Methods
// use @g_bookmark_file_add_application[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, name': Pointer[U8] tag, exec': Pointer[U8] tag)
// use @g_bookmark_file_add_group[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, group': Pointer[U8] tag)
// use @g_bookmark_file_free[None](bookmark': NullablePointer[GBookmarkFileT])
// use @g_bookmark_file_get_added[I64](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_added_date_time[NullablePointer[GDateTimeT]](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_app_info[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, name': Pointer[U8] tag, exec': Pointer[Pointer[U8]] tag, count': Pointer[U32] tag, stamp': Pointer[I64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_application_info[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, name': Pointer[U8] tag, exec': Pointer[Pointer[U8]] tag, count': Pointer[U32] tag, stamp': Pointer[NullablePointer[GDateTimeT]], error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_applications[Pointer[Pointer[U8]] tag](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_description[Pointer[U8] tag](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_groups[Pointer[Pointer[U8]] tag](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_icon[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, href': Pointer[Pointer[U8]] tag, mime_type': Pointer[Pointer[U8]] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_is_private[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_mime_type[Pointer[U8] tag](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_modified[I64](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_modified_date_time[NullablePointer[GDateTimeT]](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_size[I32](bookmark': NullablePointer[GBookmarkFileT])
// use @g_bookmark_file_get_title[Pointer[U8] tag](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_uris[Pointer[Pointer[U8]] tag](bookmark': NullablePointer[GBookmarkFileT], length': Pointer[U64] tag)
// use @g_bookmark_file_get_visited[I64](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_get_visited_date_time[NullablePointer[GDateTimeT]](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_has_application[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, name': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_has_group[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, group': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_has_item[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag)
// use @g_bookmark_file_load_from_data[I32](bookmark': NullablePointer[GBookmarkFileT], data': Pointer[U8] tag, length': U64, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_load_from_data_dirs[I32](bookmark': NullablePointer[GBookmarkFileT], file': Pointer[U8] tag, full_path': Pointer[Pointer[U8]] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_load_from_file[I32](bookmark': NullablePointer[GBookmarkFileT], filename': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_move_item[I32](bookmark': NullablePointer[GBookmarkFileT], old_uri': Pointer[U8] tag, new_uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_remove_application[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, name': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_remove_group[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, group': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_remove_item[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_set_added[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, added': I64)
// use @g_bookmark_file_set_added_date_time[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, added': NullablePointer[GDateTimeT])
// use @g_bookmark_file_set_app_info[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, name': Pointer[U8] tag, exec': Pointer[U8] tag, count': I32, stamp': I64, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_set_application_info[I32](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, name': Pointer[U8] tag, exec': Pointer[U8] tag, count': I32, stamp': NullablePointer[GDateTimeT], error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_set_description[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, description': Pointer[U8] tag)
// use @g_bookmark_file_set_groups[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, groups': Pointer[Pointer[U8]] tag, length': U64)
// use @g_bookmark_file_set_icon[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, href': Pointer[U8] tag, mime_type': Pointer[U8] tag)
// use @g_bookmark_file_set_is_private[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, is_private': I32)
// use @g_bookmark_file_set_mime_type[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, mime_type': Pointer[U8] tag)
// use @g_bookmark_file_set_modified[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, modified': I64)
// use @g_bookmark_file_set_modified_date_time[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, modified': NullablePointer[GDateTimeT])
// use @g_bookmark_file_set_title[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, title': Pointer[U8] tag)
// use @g_bookmark_file_set_visited[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, visited': I64)
// use @g_bookmark_file_set_visited_date_time[None](bookmark': NullablePointer[GBookmarkFileT], uri': Pointer[U8] tag, visited': NullablePointer[GDateTimeT])
// use @g_bookmark_file_to_data[Pointer[U8] tag](bookmark': NullablePointer[GBookmarkFileT], length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_bookmark_file_to_file[I32](bookmark': NullablePointer[GBookmarkFileT], filename': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
