
use "lib:glib-2.0"

// Static Functions
// use @g_date_get_days_in_month[U8](month': U32, year': U16)
// use @g_date_get_monday_weeks_in_year[U8](year': U16)
// use @g_date_get_sunday_weeks_in_year[U8](year': U16)
// use @g_date_is_leap_year[I32](year': U16)
// use @g_date_strftime[U64](s': Pointer[U8] tag, slen': U64, format': Pointer[U8] tag, date': GDateT)
// use @g_date_valid_day[I32](day': U8)
// use @g_date_valid_dmy[I32](day': U8, month': U32, year': U16)
// use @g_date_valid_julian[I32](julian_date': U32)
// use @g_date_valid_month[I32](month': U32)
// use @g_date_valid_weekday[I32](weekday': U32)
// use @g_date_valid_year[I32](year': U16)

// Constructors
// use @g_date_new[GDateT]()
// use @g_date_new_dmy[GDateT](day': U8, month': U32, year': U16)
// use @g_date_new_julian[GDateT](julian_day': U32)

// Methods
// use @g_date_add_days[None](date': GDateT, n_days': U32)
// use @g_date_add_months[None](date': GDateT, n_months': U32)
// use @g_date_add_years[None](date': GDateT, n_years': U32)
// use @g_date_clamp[None](date': GDateT, min_date': GDateT, max_date': GDateT)
// use @g_date_clear[None](date': GDateT, n_dates': U32)
// use @g_date_compare[I32](lhs': GDateT, rhs': GDateT)
// use @g_date_copy[GDateT](date': GDateT)
// use @g_date_days_between[I32](date1': GDateT, date2': GDateT)
// use @g_date_free[None](date': GDateT)
// use @g_date_get_day[U8](date': GDateT)
// use @g_date_get_day_of_year[U32](date': GDateT)
// use @g_date_get_iso8601_week_of_year[U32](date': GDateT)
// use @g_date_get_julian[U32](date': GDateT)
// use @g_date_get_monday_week_of_year[U32](date': GDateT)
// use @g_date_get_month[U32](date': GDateT)
// use @g_date_get_sunday_week_of_year[U32](date': GDateT)
// use @g_date_get_weekday[U32](date': GDateT)
// use @g_date_get_year[U16](date': GDateT)
// use @g_date_is_first_of_month[I32](date': GDateT)
// use @g_date_is_last_of_month[I32](date': GDateT)
// use @g_date_order[None](date1': GDateT, date2': GDateT)
// use @g_date_set_day[None](date': GDateT, day': U8)
// use @g_date_set_dmy[None](date': GDateT, day': U8, month': U32, y': U16)
// use @g_date_set_julian[None](date': GDateT, julian_date': U32)
// use @g_date_set_month[None](date': GDateT, month': U32)
// use @g_date_set_parse[None](date': GDateT, str': Pointer[U8] tag)
// use @g_date_set_time[None](date': GDateT, time_': I32)
// use @g_date_set_time_t[None](date': GDateT, timet': I64)
// use @g_date_set_time_val[None](date': GDateT, timeval': GTimeValT)
// use @g_date_set_year[None](date': GDateT, year': U16)
// use @g_date_subtract_days[None](date': GDateT, n_days': U32)
// use @g_date_subtract_months[None](date': GDateT, n_months': U32)
// use @g_date_subtract_years[None](date': GDateT, n_years': U32)
// use @g_date_to_struct_tm[None](date': GDateT, tm': tmT)
// use @g_date_valid[I32](date': GDateT)
