
use "lib:glib-2.0"

// Static Functions

// Constructors
// use @g_date_time_new[Pointer[GDateTimeT]](tz': NullablePointer[GTimeZoneT], year': I32, month': I32, day': I32, hour': I32, minute': I32, seconds': F64)
// use @g_date_time_new_from_iso8601[Pointer[GDateTimeT]](text': Pointer[U8] tag, default_tz': NullablePointer[GTimeZoneT])
// use @g_date_time_new_from_timeval_local[Pointer[GDateTimeT]](tv': NullablePointer[GTimeValT])
// use @g_date_time_new_from_timeval_utc[Pointer[GDateTimeT]](tv': NullablePointer[GTimeValT])
// use @g_date_time_new_from_unix_local[Pointer[GDateTimeT]](t': I64)
// use @g_date_time_new_from_unix_utc[Pointer[GDateTimeT]](t': I64)
// use @g_date_time_new_local[Pointer[GDateTimeT]](year': I32, month': I32, day': I32, hour': I32, minute': I32, seconds': F64)
// use @g_date_time_new_now[Pointer[GDateTimeT]](tz': NullablePointer[GTimeZoneT])
// use @g_date_time_new_now_local[Pointer[GDateTimeT]]()
// use @g_date_time_new_now_utc[Pointer[GDateTimeT]]()
// use @g_date_time_new_utc[Pointer[GDateTimeT]](year': I32, month': I32, day': I32, hour': I32, minute': I32, seconds': F64)

// Methods
// use @g_date_time_add[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], timespan': I64)
// use @g_date_time_add_days[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], days': I32)
// use @g_date_time_add_full[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], years': I32, months': I32, days': I32, hours': I32, minutes': I32, seconds': F64)
// use @g_date_time_add_hours[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], hours': I32)
// use @g_date_time_add_minutes[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], minutes': I32)
// use @g_date_time_add_months[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], months': I32)
// use @g_date_time_add_seconds[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], seconds': F64)
// use @g_date_time_add_weeks[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], weeks': I32)
// use @g_date_time_add_years[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], years': I32)
// use @g_date_time_compare[I32](dt1': Pointer[None] tag, dt2': Pointer[None] tag)
// use @g_date_time_difference[I64](end': NullablePointer[GDateTimeT], begin': NullablePointer[GDateTimeT])
// use @g_date_time_equal[I32](dt1': Pointer[None] tag, dt2': Pointer[None] tag)
// use @g_date_time_format[Pointer[U8]](datetime': NullablePointer[GDateTimeT], format': Pointer[U8] tag)
// use @g_date_time_format_iso8601[Pointer[U8]](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_day_of_month[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_day_of_week[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_day_of_year[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_hour[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_microsecond[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_minute[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_month[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_second[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_seconds[F64](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_timezone[Pointer[GTimeZoneT]](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_timezone_abbreviation[Pointer[U8]](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_utc_offset[I64](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_week_numbering_year[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_week_of_year[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_year[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_get_ymd[None](datetime': NullablePointer[GDateTimeT], year': Pointer[I32] tag, month': Pointer[I32] tag, day': Pointer[I32] tag)
// use @g_date_time_hash[U32](datetime': Pointer[None] tag)
// use @g_date_time_is_daylight_savings[I32](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_ref[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_to_local[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_to_timeval[I32](datetime': NullablePointer[GDateTimeT], tv': NullablePointer[GTimeValT])
// use @g_date_time_to_timezone[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT], tz': NullablePointer[GTimeZoneT])
// use @g_date_time_to_unix[I64](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_to_utc[Pointer[GDateTimeT]](datetime': NullablePointer[GDateTimeT])
// use @g_date_time_unref[None](datetime': NullablePointer[GDateTimeT])
