
use "lib:glib-2.0"

// Static Functions
// use @g_key_file_error_quark[U32]()

// Constructors
// use @g_key_file_new[NullablePointer[GKeyFileT]]()

// Methods
// use @g_key_file_free[None](key_file': NullablePointer[GKeyFileT])
// use @g_key_file_get_boolean[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_boolean_list[Pointer[I32] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_comment[Pointer[U8] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_double[F64](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_double_list[Pointer[F64] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_groups[Pointer[Pointer[U8]] tag](key_file': NullablePointer[GKeyFileT], length': Pointer[U64] tag)
// use @g_key_file_get_int64[I64](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_integer[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_integer_list[Pointer[I32] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_keys[Pointer[Pointer[U8]] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_locale_for_key[Pointer[U8] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, locale': Pointer[U8] tag)
// use @g_key_file_get_locale_string[Pointer[U8] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, locale': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_locale_string_list[Pointer[Pointer[U8]] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, locale': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_start_group[Pointer[U8] tag](key_file': NullablePointer[GKeyFileT])
// use @g_key_file_get_string[Pointer[U8] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_string_list[Pointer[Pointer[U8]] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_uint64[U64](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_get_value[Pointer[U8] tag](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_has_group[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag)
// use @g_key_file_has_key[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_load_from_bytes[I32](key_file': NullablePointer[GKeyFileT], bytes': NullablePointer[GBytesT], flags': U32, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_load_from_data[I32](key_file': NullablePointer[GKeyFileT], data': Pointer[U8] tag, length': U64, flags': U32, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_load_from_data_dirs[I32](key_file': NullablePointer[GKeyFileT], file': Pointer[U8] tag, full_path': Pointer[Pointer[U8]] tag, flags': U32, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_load_from_dirs[I32](key_file': NullablePointer[GKeyFileT], file': Pointer[U8] tag, search_dirs': Pointer[Pointer[U8]] tag, full_path': Pointer[Pointer[U8]] tag, flags': U32, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_load_from_file[I32](key_file': NullablePointer[GKeyFileT], file': Pointer[U8] tag, flags': U32, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_ref[NullablePointer[GKeyFileT]](key_file': NullablePointer[GKeyFileT])
// use @g_key_file_remove_comment[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_remove_group[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_remove_key[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_save_to_file[I32](key_file': NullablePointer[GKeyFileT], filename': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_set_boolean[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, value': I32)
// use @g_key_file_set_boolean_list[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, list': Pointer[I32] tag, length': U64)
// use @g_key_file_set_comment[I32](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, comment': Pointer[U8] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_set_double[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, value': F64)
// use @g_key_file_set_double_list[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, list': Pointer[F64] tag, length': U64)
// use @g_key_file_set_int64[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, value': I64)
// use @g_key_file_set_integer[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, value': I32)
// use @g_key_file_set_integer_list[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, list': Pointer[I32] tag, length': U64)
// use @g_key_file_set_list_separator[None](key_file': NullablePointer[GKeyFileT], separator': U8)
// use @g_key_file_set_locale_string[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, locale': Pointer[U8] tag, string': Pointer[U8] tag)
// use @g_key_file_set_locale_string_list[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, locale': Pointer[U8] tag, list': Pointer[Pointer[U8]] tag, length': U64)
// use @g_key_file_set_string[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, string': Pointer[U8] tag)
// use @g_key_file_set_string_list[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, list': Pointer[Pointer[U8]] tag, length': U64)
// use @g_key_file_set_uint64[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, value': U64)
// use @g_key_file_set_value[None](key_file': NullablePointer[GKeyFileT], group_name': Pointer[U8] tag, key': Pointer[U8] tag, value': Pointer[U8] tag)
// use @g_key_file_to_data[Pointer[U8] tag](key_file': NullablePointer[GKeyFileT], length': Pointer[U64] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_key_file_unref[None](key_file': NullablePointer[GKeyFileT])
