
use "lib:glib-2.0"

// Static Functions
// use @g_variant_is_object_path[I32](string': Pointer[U8] tag)
// use @g_variant_is_signature[I32](string': Pointer[U8] tag)
// use @g_variant_parse[NullablePointer[GVariantT]](type': NullablePointer[GVariantTypeT], text': Pointer[U8] tag, limit': Pointer[U8] tag, endptr': Pointer[Pointer[U8]] tag, error': Pointer[NullablePointer[GErrorT]])
// use @g_variant_parse_error_print_context[Pointer[U8] tag](error': NullablePointer[GErrorT], source_str': Pointer[U8] tag)
// use @g_variant_parse_error_quark[U32]()
// use @g_variant_parser_get_error_quark[U32]()

// Constructors
// use @g_variant_new[NullablePointer[GVariantT]](format_string': Pointer[U8] tag, ...)
// use @g_variant_new_array[NullablePointer[GVariantT]](child_type': NullablePointer[GVariantTypeT], children': Pointer[NullablePointer[GVariantT]], n_children': U64)
// use @g_variant_new_boolean[NullablePointer[GVariantT]](value': I32)
// use @g_variant_new_byte[NullablePointer[GVariantT]](value': U8)
// use @g_variant_new_bytestring[NullablePointer[GVariantT]](string': Pointer[U8] tag)
// use @g_variant_new_bytestring_array[NullablePointer[GVariantT]](strv': Pointer[Pointer[U8]] tag, length': I64)
// use @g_variant_new_dict_entry[NullablePointer[GVariantT]](key': NullablePointer[GVariantT], value': NullablePointer[GVariantT])
// use @g_variant_new_double[NullablePointer[GVariantT]](value': F64)
// use @g_variant_new_fixed_array[NullablePointer[GVariantT]](element_type': NullablePointer[GVariantTypeT], elements': Pointer[None] tag, n_elements': U64, element_size': U64)
// use @g_variant_new_from_bytes[NullablePointer[GVariantT]](type': NullablePointer[GVariantTypeT], bytes': NullablePointer[GBytesT], trusted': I32)
// use @g_variant_new_from_data[NullablePointer[GVariantT]](type': NullablePointer[GVariantTypeT], data': Pointer[None] tag, size': U64, trusted': I32, notify': GDestroyNotify, user_data': Pointer[None] tag)
// use @g_variant_new_handle[NullablePointer[GVariantT]](value': I32)
// use @g_variant_new_int16[NullablePointer[GVariantT]](value': I16)
// use @g_variant_new_int32[NullablePointer[GVariantT]](value': I32)
// use @g_variant_new_int64[NullablePointer[GVariantT]](value': I64)
// use @g_variant_new_maybe[NullablePointer[GVariantT]](child_type': NullablePointer[GVariantTypeT], child': NullablePointer[GVariantT])
// use @g_variant_new_object_path[NullablePointer[GVariantT]](object_path': Pointer[U8] tag)
// use @g_variant_new_objv[NullablePointer[GVariantT]](strv': Pointer[Pointer[U8]] tag, length': I64)
// use @g_variant_new_parsed[NullablePointer[GVariantT]](format': Pointer[U8] tag, ...)
// use @g_variant_new_printf[NullablePointer[GVariantT]](format_string': Pointer[U8] tag, ...)
// use @g_variant_new_signature[NullablePointer[GVariantT]](signature': Pointer[U8] tag)
// use @g_variant_new_string[NullablePointer[GVariantT]](string': Pointer[U8] tag)
// use @g_variant_new_strv[NullablePointer[GVariantT]](strv': Pointer[Pointer[U8]] tag, length': I64)
// use @g_variant_new_take_string[NullablePointer[GVariantT]](string': Pointer[U8] tag)
// use @g_variant_new_tuple[NullablePointer[GVariantT]](children': Pointer[NullablePointer[GVariantT]], n_children': U64)
// use @g_variant_new_uint16[NullablePointer[GVariantT]](value': U16)
// use @g_variant_new_uint32[NullablePointer[GVariantT]](value': U32)
// use @g_variant_new_uint64[NullablePointer[GVariantT]](value': U64)
// use @g_variant_new_variant[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])

// Methods
// use @g_variant_byteswap[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])
// use @g_variant_check_format_string[I32](value': NullablePointer[GVariantT], format_string': Pointer[U8] tag, copy_only': I32)
// use @g_variant_classify[U32](value': NullablePointer[GVariantT])
// use @g_variant_compare[I32](one': Pointer[None] tag, two': Pointer[None] tag)
// use @g_variant_dup_bytestring[Pointer[U8] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_dup_bytestring_array[Pointer[Pointer[U8]] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_dup_objv[Pointer[Pointer[U8]] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_dup_string[Pointer[U8] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_dup_strv[Pointer[Pointer[U8]] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_equal[I32](one': Pointer[None] tag, two': Pointer[None] tag)
// use @g_variant_get[None](value': NullablePointer[GVariantT], format_string': Pointer[U8] tag, ...)
// use @g_variant_get_boolean[I32](value': NullablePointer[GVariantT])
// use @g_variant_get_byte[U8](value': NullablePointer[GVariantT])
// use @g_variant_get_bytestring[Pointer[U8] tag](value': NullablePointer[GVariantT])
// use @g_variant_get_bytestring_array[Pointer[Pointer[U8]] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_get_child[None](value': NullablePointer[GVariantT], index_': U64, format_string': Pointer[U8] tag, ...)
// use @g_variant_get_child_value[NullablePointer[GVariantT]](value': NullablePointer[GVariantT], index_': U64)
// use @g_variant_get_data[Pointer[None] tag](value': NullablePointer[GVariantT])
// use @g_variant_get_data_as_bytes[NullablePointer[GBytesT]](value': NullablePointer[GVariantT])
// use @g_variant_get_double[F64](value': NullablePointer[GVariantT])
// use @g_variant_get_fixed_array[Pointer[None] tag](value': NullablePointer[GVariantT], n_elements': Pointer[U64] tag, element_size': U64)
// use @g_variant_get_handle[I32](value': NullablePointer[GVariantT])
// use @g_variant_get_int16[I16](value': NullablePointer[GVariantT])
// use @g_variant_get_int32[I32](value': NullablePointer[GVariantT])
// use @g_variant_get_int64[I64](value': NullablePointer[GVariantT])
// use @g_variant_get_maybe[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])
// use @g_variant_get_normal_form[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])
// use @g_variant_get_objv[Pointer[Pointer[U8]] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_get_size[U64](value': NullablePointer[GVariantT])
// use @g_variant_get_string[Pointer[U8] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_get_strv[Pointer[Pointer[U8]] tag](value': NullablePointer[GVariantT], length': Pointer[U64] tag)
// use @g_variant_get_type[NullablePointer[GVariantTypeT]](value': NullablePointer[GVariantT])
// use @g_variant_get_type_string[Pointer[U8] tag](value': NullablePointer[GVariantT])
// use @g_variant_get_uint16[U16](value': NullablePointer[GVariantT])
// use @g_variant_get_uint32[U32](value': NullablePointer[GVariantT])
// use @g_variant_get_uint64[U64](value': NullablePointer[GVariantT])
// use @g_variant_get_variant[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])
// use @g_variant_hash[U32](value': Pointer[None] tag)
// use @g_variant_is_container[I32](value': NullablePointer[GVariantT])
// use @g_variant_is_floating[I32](value': NullablePointer[GVariantT])
// use @g_variant_is_normal_form[I32](value': NullablePointer[GVariantT])
// use @g_variant_is_of_type[I32](value': NullablePointer[GVariantT], type': NullablePointer[GVariantTypeT])
// use @g_variant_iter_new[NullablePointer[GVariantIterT]](value': NullablePointer[GVariantT])
// use @g_variant_lookup[I32](dictionary': NullablePointer[GVariantT], key': Pointer[U8] tag, format_string': Pointer[U8] tag, ...)
// use @g_variant_lookup_value[NullablePointer[GVariantT]](dictionary': NullablePointer[GVariantT], key': Pointer[U8] tag, expected_type': NullablePointer[GVariantTypeT])
// use @g_variant_n_children[U64](value': NullablePointer[GVariantT])
// use @g_variant_print[Pointer[U8] tag](value': NullablePointer[GVariantT], type_annotate': I32)
// use @g_variant_print_string[NullablePointer[GStringT]](value': NullablePointer[GVariantT], string': NullablePointer[GStringT], type_annotate': I32)
// use @g_variant_ref[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])
// use @g_variant_ref_sink[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])
// use @g_variant_store[None](value': NullablePointer[GVariantT], data': Pointer[None] tag)
// use @g_variant_take_ref[NullablePointer[GVariantT]](value': NullablePointer[GVariantT])
// use @g_variant_unref[None](value': NullablePointer[GVariantT])
