
use "../GLib"
use "../GObject"
use "lib:gio-2.0"

// Static Functions
// use @g_dbus_message_bytes_needed[I64](blob': Pointer[U8] tag, blob_len': U64, error': Pointer[NullablePointer[GErrorT]])

// Constructors
// use @g_dbus_message_new[NullablePointer[GDBusMessageT]]()
// use @g_dbus_message_new_from_blob[NullablePointer[GDBusMessageT]](blob': Pointer[U8] tag, blob_len': U64, capabilities': U32, error': Pointer[NullablePointer[GErrorT]])
// use @g_dbus_message_new_method_call[NullablePointer[GDBusMessageT]](name': Pointer[U8] tag, path': Pointer[U8] tag, interface_': Pointer[U8] tag, method': Pointer[U8] tag)
// use @g_dbus_message_new_signal[NullablePointer[GDBusMessageT]](path': Pointer[U8] tag, interface_': Pointer[U8] tag, signal': Pointer[U8] tag)

// Methods
// use @g_dbus_message_copy[NullablePointer[GDBusMessageT]](message': NullablePointer[GDBusMessageT], error': Pointer[NullablePointer[GErrorT]])
// use @g_dbus_message_get_arg0[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_body[NullablePointer[GVariantT]](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_byte_order[U32](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_destination[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_error_name[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_flags[U32](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_header[NullablePointer[GVariantT]](message': NullablePointer[GDBusMessageT], header_field': U32)
// use @g_dbus_message_get_header_fields[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_interface[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_locked[I32](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_member[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_message_type[U32](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_num_unix_fds[U32](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_path[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_reply_serial[U32](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_sender[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_serial[U32](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_signature[Pointer[U8] tag](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_get_unix_fd_list[NullablePointer[GUnixFDListT]](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_lock[None](message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_new_method_error[NullablePointer[GDBusMessageT]](method_call_message': NullablePointer[GDBusMessageT], error_name': Pointer[U8] tag, error_message_format': Pointer[U8] tag, ...)
// use @g_dbus_message_new_method_error_literal[NullablePointer[GDBusMessageT]](method_call_message': NullablePointer[GDBusMessageT], error_name': Pointer[U8] tag, error_message': Pointer[U8] tag)
// use @g_dbus_message_new_method_error_valist[NullablePointer[GDBusMessageT]](method_call_message': NullablePointer[GDBusMessageT], error_name': Pointer[U8] tag, error_message_format': Pointer[U8] tag, var_args': NullablePointer[valisttagT])
// use @g_dbus_message_new_method_reply[NullablePointer[GDBusMessageT]](method_call_message': NullablePointer[GDBusMessageT])
// use @g_dbus_message_print[Pointer[U8] tag](message': NullablePointer[GDBusMessageT], indent': U32)
// use @g_dbus_message_set_body[None](message': NullablePointer[GDBusMessageT], body': NullablePointer[GVariantT])
// use @g_dbus_message_set_byte_order[None](message': NullablePointer[GDBusMessageT], byte_order': U32)
// use @g_dbus_message_set_destination[None](message': NullablePointer[GDBusMessageT], value': Pointer[U8] tag)
// use @g_dbus_message_set_error_name[None](message': NullablePointer[GDBusMessageT], value': Pointer[U8] tag)
// use @g_dbus_message_set_flags[None](message': NullablePointer[GDBusMessageT], flags': U32)
// use @g_dbus_message_set_header[None](message': NullablePointer[GDBusMessageT], header_field': U32, value': NullablePointer[GVariantT])
// use @g_dbus_message_set_interface[None](message': NullablePointer[GDBusMessageT], value': Pointer[U8] tag)
// use @g_dbus_message_set_member[None](message': NullablePointer[GDBusMessageT], value': Pointer[U8] tag)
// use @g_dbus_message_set_message_type[None](message': NullablePointer[GDBusMessageT], type': U32)
// use @g_dbus_message_set_num_unix_fds[None](message': NullablePointer[GDBusMessageT], value': U32)
// use @g_dbus_message_set_path[None](message': NullablePointer[GDBusMessageT], value': Pointer[U8] tag)
// use @g_dbus_message_set_reply_serial[None](message': NullablePointer[GDBusMessageT], value': U32)
// use @g_dbus_message_set_sender[None](message': NullablePointer[GDBusMessageT], value': Pointer[U8] tag)
// use @g_dbus_message_set_serial[None](message': NullablePointer[GDBusMessageT], serial': U32)
// use @g_dbus_message_set_signature[None](message': NullablePointer[GDBusMessageT], value': Pointer[U8] tag)
// use @g_dbus_message_set_unix_fd_list[None](message': NullablePointer[GDBusMessageT], fd_list': NullablePointer[GUnixFDListT])
// use @g_dbus_message_to_blob[Pointer[U8] tag](message': NullablePointer[GDBusMessageT], out_size': Pointer[U64] tag, capabilities': U32, error': Pointer[NullablePointer[GErrorT]])
// use @g_dbus_message_to_gerror[I32](message': NullablePointer[GDBusMessageT], error': Pointer[NullablePointer[GErrorT]])
