
// Static Functions
// use @g_settings_list_relocatable_schemas[Pointer[Pointer[U8]]]()
// use @g_settings_list_schemas[Pointer[Pointer[U8]]]()
// use @g_settings_sync[None]()
// use @g_settings_unbind[None](object': Pointer[None] tag, property': Pointer[U8] tag)

// Constructors
// use @g_settings_new[Pointer[GSettingsT]](schema_id': Pointer[U8] tag)
// use @g_settings_new_full[Pointer[GSettingsT]](schema': NullablePointer[GSettingsSchemaT], backend': NullablePointer[GSettingsBackendT], path': Pointer[U8] tag)
// use @g_settings_new_with_backend[Pointer[GSettingsT]](schema_id': Pointer[U8] tag, backend': NullablePointer[GSettingsBackendT])
// use @g_settings_new_with_backend_and_path[Pointer[GSettingsT]](schema_id': Pointer[U8] tag, backend': NullablePointer[GSettingsBackendT], path': Pointer[U8] tag)
// use @g_settings_new_with_path[Pointer[GSettingsT]](schema_id': Pointer[U8] tag, path': Pointer[U8] tag)

// Methods
// use @g_settings_apply[None](settings': NullablePointer[GSettingsT])
// use @g_settings_bind[None](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, object': Pointer[None] tag, property': Pointer[U8] tag, flags': U32)
// use @g_settings_bind_writable[None](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, object': Pointer[None] tag, property': Pointer[U8] tag, inverted': I32)
// use @g_settings_create_action[Pointer[GActionT]](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_delay[None](settings': NullablePointer[GSettingsT])
// use @g_settings_get[None](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, format': Pointer[U8] tag, ...)
// use @g_settings_get_boolean[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_child[Pointer[GSettingsT]](settings': NullablePointer[GSettingsT], name': Pointer[U8] tag)
// use @g_settings_get_default_value[Pointer[GVariantT]](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_double[F64](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_enum[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_flags[U32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_has_unapplied[I32](settings': NullablePointer[GSettingsT])
// use @g_settings_get_int[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_int64[I64](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_range[Pointer[GVariantT]](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_string[Pointer[U8]](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_strv[Pointer[Pointer[U8]]](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_uint[U32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_uint64[U64](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_user_value[Pointer[GVariantT]](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_get_value[Pointer[GVariantT]](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_is_writable[I32](settings': NullablePointer[GSettingsT], name': Pointer[U8] tag)
// use @g_settings_list_children[Pointer[Pointer[U8]]](settings': NullablePointer[GSettingsT])
// use @g_settings_list_keys[Pointer[Pointer[U8]]](settings': NullablePointer[GSettingsT])
// use @g_settings_range_check[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': NullablePointer[GVariantT])
// use @g_settings_reset[None](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag)
// use @g_settings_revert[None](settings': NullablePointer[GSettingsT])
// use @g_settings_set[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, format': Pointer[U8] tag, ...)
// use @g_settings_set_boolean[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': I32)
// use @g_settings_set_double[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': F64)
// use @g_settings_set_enum[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': I32)
// use @g_settings_set_flags[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': U32)
// use @g_settings_set_int[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': I32)
// use @g_settings_set_int64[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': I64)
// use @g_settings_set_string[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': Pointer[U8] tag)
// use @g_settings_set_strv[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': Pointer[Pointer[U8]] tag)
// use @g_settings_set_uint[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': U32)
// use @g_settings_set_uint64[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': U64)
// use @g_settings_set_value[I32](settings': NullablePointer[GSettingsT], key': Pointer[U8] tag, value': NullablePointer[GVariantT])
