inventory:
	saxon-he -xi Gdk-4.0.gir ../xslt/inventory.xsl > Gdk.inv
	saxon-he -xi cairo-1.0.gir ../xslt/inventory.xsl > cairo.inv
	saxon-he -xi GdkPixbuf-2.0.gir ../xslt/inventory.xsl > GdkPixbuf.inv
	saxon-he -xi Gio-2.0.gir ../xslt/inventory.xsl > Gio.inv
	saxon-he -xi GLib-2.0.gir ../xslt/inventory.xsl > GLib.inv
	saxon-he -xi GModule-2.0.gir ../xslt/inventory.xsl > GModule.inv
	saxon-he -xi GObject-2.0.gir ../xslt/inventory.xsl > GObject.inv
	saxon-he -xi Graphene-1.0.gir ../xslt/inventory.xsl > Graphene.inv
	saxon-he -xi Gsk-4.0.gir ../xslt/inventory.xsl > Gsk.inv
	saxon-he -xi Gtk-4.0.gir ../xslt/inventory.xsl > Gtk.inv
	saxon-he -xi HarfBuzz-0.0.gir ../xslt/inventory.xsl > HarfBuzz.inv
	saxon-he -xi Pango-1.0.gir ../xslt/inventory.xsl > Pango.inv
	saxon-he -xi PangoCairo-1.0.gir ../xslt/inventory.xsl > PangoCairo.inv
