
use:
	saxon-he -xi main.xml ../../xsl/makeuse.xsl namespace=GObject debug=1

sys:
	saxon-he -xi main.xml ../../xsl/makesys.xsl namespace=GObject debug=1

struct:
	saxon-he -xi main.xml ../../xsl/makestruct.xsl namespace=GObject debug=1

class:
	saxon-he -xi main.xml ../../xsl/makeclass.xsl namespace=GObject debug=1

clean:
	rm -rf ../templates/GObject
