
use "../GLib"
use "lib:gobject-2.0"

// Static Functions
// use @g_cclosure_marshal_BOOLEAN__BOXED_BOXED[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_BOOLEAN__FLAGS[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_BOOLEAN__FLAGSv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_STRING__OBJECT_POINTER[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_STRING__OBJECT_POINTERv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__BOOLEAN[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__BOOLEANv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__BOXED[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__BOXEDv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__CHAR[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__CHARv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__DOUBLE[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__DOUBLEv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__ENUM[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__ENUMv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__FLAGS[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__FLAGSv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__FLOAT[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__FLOATv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__INT[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__INTv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__LONG[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__LONGv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__OBJECT[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__OBJECTv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__PARAM[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__PARAMv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__POINTER[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__POINTERv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__STRING[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__STRINGv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__UCHAR[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__UCHARv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__UINT[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__UINT_POINTER[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__UINT_POINTERv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__UINTv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__ULONG[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__ULONGv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__VARIANT[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__VARIANTv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_VOID__VOID[None](closure': GClosureT, return_value': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_VOID__VOIDv[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_marshal_generic[None](closure': GClosureT, return_gvalue': GValueT, n_param_values': U32, param_values': GValueT, invocation_hint': Pointer[None] tag, marshal_data': Pointer[None] tag)
// use @g_cclosure_marshal_generic_va[None](closure': GClosureT, return_value': GValueT, instance': Pointer[None] tag, args_list': valisttagT, marshal_data': Pointer[None] tag, n_params': I32, param_types': Pointer[U64] tag)
// use @g_cclosure_new[GClosureT](callback_func': GCallback, user_data': Pointer[None] tag, destroy_data': GClosureNotify)
// use @g_cclosure_new_object[GClosureT](callback_func': GCallback, object': GObjectT)
// use @g_cclosure_new_object_swap[GClosureT](callback_func': GCallback, object': GObjectT)
// use @g_cclosure_new_swap[GClosureT](callback_func': GCallback, user_data': Pointer[None] tag, destroy_data': GClosureNotify)

// Constructors

// Methods
