
use "../GLib"
use "lib:gobject-2.0"
// use @g_boxed_copy[Pointer[None]](boxed_type': U64, src_boxed': Pointer[None] tag)
// use @g_boxed_free[None](boxed_type': U64, boxed': Pointer[None] tag)
// use @g_clear_object[None](object_ptr': Pointer[NullablePointer[GObjectT]])
// use @g_clear_signal_handler[None](handler_id_ptr': Pointer[U64] tag, instance': Pointer[None] tag)
// use @g_enum_complete_type_info[None](g_enum_type': U64, info': NullablePointer[GTypeInfoT], const_values': NullablePointer[GEnumValueT])
// use @g_enum_get_value[Pointer[GEnumValueT]](enum_class': NullablePointer[GEnumClassT], value': I32)
// use @g_enum_get_value_by_name[Pointer[GEnumValueT]](enum_class': NullablePointer[GEnumClassT], name': Pointer[U8] tag)
// use @g_enum_get_value_by_nick[Pointer[GEnumValueT]](enum_class': NullablePointer[GEnumClassT], nick': Pointer[U8] tag)
// use @g_enum_register_static[U64](name': Pointer[U8] tag, const_static_values': NullablePointer[GEnumValueT])
// use @g_enum_to_string[Pointer[U8]](g_enum_type': U64, value': I32)
// use @g_flags_complete_type_info[None](g_flags_type': U64, info': NullablePointer[GTypeInfoT], const_values': NullablePointer[GFlagsValueT])
// use @g_flags_get_first_value[Pointer[GFlagsValueT]](flags_class': NullablePointer[GFlagsClassT], value': U32)
// use @g_flags_get_value_by_name[Pointer[GFlagsValueT]](flags_class': NullablePointer[GFlagsClassT], name': Pointer[U8] tag)
// use @g_flags_get_value_by_nick[Pointer[GFlagsValueT]](flags_class': NullablePointer[GFlagsClassT], nick': Pointer[U8] tag)
// use @g_flags_register_static[U64](name': Pointer[U8] tag, const_static_values': NullablePointer[GFlagsValueT])
// use @g_flags_to_string[Pointer[U8]](flags_type': U64, value': U32)
// use @g_gtype_get_type[U64]()
// use @g_param_spec_boolean[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, default_value': I32, flags': I32)
// use @g_param_spec_boxed[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, boxed_type': U64, flags': I32)
// use @g_param_spec_char[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': I8, maximum': I8, default_value': I8, flags': I32)
// use @g_param_spec_double[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': F64, maximum': F64, default_value': F64, flags': I32)
// use @g_param_spec_enum[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, enum_type': U64, default_value': I32, flags': I32)
// use @g_param_spec_flags[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, flags_type': U64, default_value': U32, flags': I32)
// use @g_param_spec_float[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': F32, maximum': F32, default_value': F32, flags': I32)
// use @g_param_spec_gtype[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, is_a_type': U64, flags': I32)
// use @g_param_spec_int[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': I32, maximum': I32, default_value': I32, flags': I32)
// use @g_param_spec_int64[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': I64, maximum': I64, default_value': I64, flags': I32)
// use @g_param_spec_long[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': I64, maximum': I64, default_value': I64, flags': I32)
// use @g_param_spec_object[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, object_type': U64, flags': I32)
// use @g_param_spec_override[Pointer[GParamSpecT]](name': Pointer[U8] tag, overridden': NullablePointer[GParamSpecT])
// use @g_param_spec_param[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, param_type': U64, flags': I32)
// use @g_param_spec_pointer[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, flags': I32)
// use @g_param_spec_string[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, default_value': Pointer[U8] tag, flags': I32)
// use @g_param_spec_uchar[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': U8, maximum': U8, default_value': U8, flags': I32)
// use @g_param_spec_uint[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': U32, maximum': U32, default_value': U32, flags': I32)
// use @g_param_spec_uint64[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': U64, maximum': U64, default_value': U64, flags': I32)
// use @g_param_spec_ulong[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, minimum': U64, maximum': U64, default_value': U64, flags': I32)
// use @g_param_spec_unichar[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, default_value': U32, flags': I32)
// use @g_param_spec_value_array[Pointer[GParamSpecT]](name': Pointer[U8] tag, nick': Pointer[U8] tag, blurb': Pointer[U8] tag, element_spec': NullablePointer[GParamSpecT], flags': I32)
// use @g_param_type_register_static[U64](name': Pointer[U8] tag, pspec_info': NullablePointer[GParamSpecTypeInfoT])
// use @g_param_value_convert[I32](pspec': NullablePointer[GParamSpecT], src_value': NullablePointer[GValueT], dest_value': NullablePointer[GValueT], strict_validation': I32)
// use @g_param_value_defaults[I32](pspec': NullablePointer[GParamSpecT], value': NullablePointer[GValueT])
// use @g_param_value_set_default[None](pspec': NullablePointer[GParamSpecT], value': NullablePointer[GValueT])
// use @g_param_value_validate[I32](pspec': NullablePointer[GParamSpecT], value': NullablePointer[GValueT])
// use @g_param_values_cmp[I32](pspec': NullablePointer[GParamSpecT], value1': NullablePointer[GValueT], value2': NullablePointer[GValueT])
// use @g_pointer_type_register_static[U64](name': Pointer[U8] tag)
// use @g_signal_accumulator_first_wins[I32](ihint': NullablePointer[GSignalInvocationHintT], return_accu': NullablePointer[GValueT], handler_return': NullablePointer[GValueT], dummy': Pointer[None] tag)
// use @g_signal_accumulator_true_handled[I32](ihint': NullablePointer[GSignalInvocationHintT], return_accu': NullablePointer[GValueT], handler_return': NullablePointer[GValueT], dummy': Pointer[None] tag)
// use @g_signal_chain_from_overridden[None](instance_and_params': NullablePointer[GValueT], return_value': NullablePointer[GValueT])
// use @g_signal_chain_from_overridden_handler[None](instance': Pointer[None] tag, ...)
// use @g_signal_connect_closure[U64](instance': Pointer[None] tag, detailed_signal': Pointer[U8] tag, closure': NullablePointer[GClosureT], after': I32)
// use @g_signal_connect_closure_by_id[U64](instance': Pointer[None] tag, signal_id': U32, detail': U32, closure': NullablePointer[GClosureT], after': I32)
// use @g_signal_emit[None](instance': Pointer[None] tag, signal_id': U32, detail': U32, ...)
// use @g_signal_emit_by_name[None](instance': Pointer[None] tag, detailed_signal': Pointer[U8] tag, ...)
// use @g_signal_emit_valist[None](instance': Pointer[None] tag, signal_id': U32, detail': U32, var_args': NullablePointer[valisttagT])
// use @g_signal_emitv[None](instance_and_params': NullablePointer[GValueT], signal_id': U32, detail': U32, return_value': NullablePointer[GValueT])
// use @g_signal_get_invocation_hint[Pointer[GSignalInvocationHintT]](instance': Pointer[None] tag)
// use @g_signal_handler_block[None](instance': Pointer[None] tag, handler_id': U64)
// use @g_signal_handler_disconnect[None](instance': Pointer[None] tag, handler_id': U64)
// use @g_signal_handler_find[U64](instance': Pointer[None] tag, mask': U32, signal_id': U32, detail': U32, closure': NullablePointer[GClosureT], func': Pointer[None] tag, data': Pointer[None] tag)
// use @g_signal_handler_is_connected[I32](instance': Pointer[None] tag, handler_id': U64)
// use @g_signal_handler_unblock[None](instance': Pointer[None] tag, handler_id': U64)
// use @g_signal_handlers_block_matched[U32](instance': Pointer[None] tag, mask': U32, signal_id': U32, detail': U32, closure': NullablePointer[GClosureT], func': Pointer[None] tag, data': Pointer[None] tag)
// use @g_signal_handlers_destroy[None](instance': Pointer[None] tag)
// use @g_signal_handlers_disconnect_matched[U32](instance': Pointer[None] tag, mask': U32, signal_id': U32, detail': U32, closure': NullablePointer[GClosureT], func': Pointer[None] tag, data': Pointer[None] tag)
// use @g_signal_handlers_unblock_matched[U32](instance': Pointer[None] tag, mask': U32, signal_id': U32, detail': U32, closure': NullablePointer[GClosureT], func': Pointer[None] tag, data': Pointer[None] tag)
// use @g_signal_has_handler_pending[I32](instance': Pointer[None] tag, signal_id': U32, detail': U32, may_be_blocked': I32)
// use @g_signal_is_valid_name[I32](name': Pointer[U8] tag)
// use @g_signal_list_ids[Pointer[U32]](itype': U64, n_ids': Pointer[U32] tag)
// use @g_signal_lookup[U32](name': Pointer[U8] tag, itype': U64)
// use @g_signal_name[Pointer[U8]](signal_id': U32)
// use @g_signal_override_class_closure[None](signal_id': U32, instance_type': U64, class_closure': NullablePointer[GClosureT])
// use @g_signal_parse_name[I32](detailed_signal': Pointer[U8] tag, itype': U64, signal_id_p': Pointer[U32] tag, detail_p': Pointer[U32] tag, force_detail_quark': I32)
// use @g_signal_query[None](signal_id': U32, query': NullablePointer[GSignalQueryT])
// use @g_signal_remove_emission_hook[None](signal_id': U32, hook_id': U64)
// use @g_signal_stop_emission[None](instance': Pointer[None] tag, signal_id': U32, detail': U32)
// use @g_signal_stop_emission_by_name[None](instance': Pointer[None] tag, detailed_signal': Pointer[U8] tag)
// use @g_signal_type_cclosure_new[Pointer[GClosureT]](itype': U64, struct_offset': U32)
// use @g_source_set_closure[None](source': NullablePointer[GSourceT], closure': NullablePointer[GClosureT])
// use @g_source_set_dummy_callback[None](source': NullablePointer[GSourceT])
// use @g_strdup_value_contents[Pointer[U8]](value': NullablePointer[GValueT])
// use @g_type_add_class_private[None](class_type': U64, private_size': U64)
// use @g_type_add_instance_private[I32](class_type': U64, private_size': U64)
// use @g_type_add_interface_dynamic[None](instance_type': U64, interface_type': U64, plugin': NullablePointer[GTypePluginT])
// use @g_type_add_interface_static[None](instance_type': U64, interface_type': U64, info': NullablePointer[GInterfaceInfoT])
// use @g_type_check_class_cast[Pointer[GTypeClassT]](g_class': NullablePointer[GTypeClassT], is_a_type': U64)
// use @g_type_check_class_is_a[I32](g_class': NullablePointer[GTypeClassT], is_a_type': U64)
// use @g_type_check_instance[I32](instance': NullablePointer[GTypeInstanceT])
// use @g_type_check_instance_cast[Pointer[GTypeInstanceT]](instance': NullablePointer[GTypeInstanceT], iface_type': U64)
// use @g_type_check_instance_is_a[I32](instance': NullablePointer[GTypeInstanceT], iface_type': U64)
// use @g_type_check_instance_is_fundamentally_a[I32](instance': NullablePointer[GTypeInstanceT], fundamental_type': U64)
// use @g_type_check_is_value_type[I32](type': U64)
// use @g_type_check_value[I32](value': NullablePointer[GValueT])
// use @g_type_check_value_holds[I32](value': NullablePointer[GValueT], type': U64)
// use @g_type_children[Pointer[U64]](type': U64, n_children': Pointer[U32] tag)
// use @g_type_create_instance[Pointer[GTypeInstanceT]](type': U64)
// use @g_type_default_interface_peek[Pointer[None]](g_type': U64)
// use @g_type_default_interface_ref[Pointer[None]](g_type': U64)
// use @g_type_default_interface_unref[None](g_iface': Pointer[None] tag)
// use @g_type_depth[U32](type': U64)
// use @g_type_ensure[None](type': U64)
// use @g_type_free_instance[None](instance': NullablePointer[GTypeInstanceT])
// use @g_type_from_name[U64](name': Pointer[U8] tag)
// use @g_type_fundamental[U64](type_id': U64)
// use @g_type_fundamental_next[U64]()
// use @g_type_get_instance_count[I32](type': U64)
// use @g_type_get_plugin[Pointer[GTypePluginT]](type': U64)
// use @g_type_get_qdata[Pointer[None]](type': U64, quark': U32)
// use @g_type_get_type_registration_serial[U32]()
// use @g_type_init[None]()
// use @g_type_init_with_debug_flags[None](debug_flags': U32)
// use @g_type_interfaces[Pointer[U64]](type': U64, n_interfaces': Pointer[U32] tag)
// use @g_type_is_a[I32](type': U64, is_a_type': U64)
// use @g_type_name[Pointer[U8]](type': U64)
// use @g_type_name_from_class[Pointer[U8]](g_class': NullablePointer[GTypeClassT])
// use @g_type_name_from_instance[Pointer[U8]](instance': NullablePointer[GTypeInstanceT])
// use @g_type_next_base[U64](leaf_type': U64, root_type': U64)
// use @g_type_parent[U64](type': U64)
// use @g_type_qname[U32](type': U64)
// use @g_type_query[None](type': U64, query': NullablePointer[GTypeQueryT])
// use @g_type_register_dynamic[U64](parent_type': U64, type_name': Pointer[U8] tag, plugin': NullablePointer[GTypePluginT], flags': U32)
// use @g_type_register_fundamental[U64](type_id': U64, type_name': Pointer[U8] tag, info': NullablePointer[GTypeInfoT], finfo': NullablePointer[GTypeFundamentalInfoT], flags': U32)
// use @g_type_register_static[U64](parent_type': U64, type_name': Pointer[U8] tag, info': NullablePointer[GTypeInfoT], flags': U32)
// use @g_type_set_qdata[None](type': U64, quark': U32, data': Pointer[None] tag)
// use @g_type_test_flags[I32](type': U64, flags': U32)
